In [ ]:
len(questions)

100

In [ ]:
import pandas as pd
question = pd.DataFrame({'문제': questions})

In [ ]:
# prompt: question csv로

question.to_csv('questions.csv', index=False, encoding='utf-8-sig')

In [ ]:
# prompt: 대구 있는 line들만 저장하는법

from google.colab import drive
import zipfile
import os

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import csv

input_file = "/content/drive/MyDrive/ninewatt/mart_djy_03.txt"
output_file = "building.csv"

with open(input_file, "r", encoding="utf-8") as txt_file, \
     open(output_file, "w", newline="", encoding="utf-8") as csv_file:

    writer = csv.writer(csv_file)

    for i, line in enumerate(txt_file, start=1):
        print(i)

        if "대구광역시" in line:
            items = line.strip().split('|')
            writer.writerow(items)
            print('-------------------')
            print(line)


print(f"'대구광역시' 포함된 행만 CSV로 저장 완료: {output_file}")

Streaming output truncated to the last 5000 lines.
767489
767490
767491
767492
767493
767494
767495
767496
767497
767498
767499
767500
767501
767502
767503
767504
767505
767506
767507
767508
767509
767510
767511
767512
767513
767514
767515
767516
767517
767518
767519
767520
767521
767522
767523
767524
767525
767526
767527
767528
767529
767530
767531
767532
767533
767534
767535
767536
767537
767538
767539
767540
767541
767542
767543
767544
767545
767546
767547
767548
767549
767550
767551
767552
767553
767554
767555
767556
767557
767558
767559
767560
767561
767562
767563
767564
767565
767566
767567
767568
767569
767570
767571
767572
767573
767574
767575
767576
767577
767578
767579
767580
767581
767582
767583
767584
767585
767586
767587
767588
767589
767590
767591
767592
767593
767594
767595
767596
767597
767598
767599
767600
767601
767602
767603
767604
767605
767606
767607
767608
767609
767610
767611
767612
767613
767614
767615
767616
767617
767618
767619
767620
767621
767622
767623
767624
767625
767626
767627
767628
767629
767630
767631
767632
767633
767634
767635
767636
767637
767638
767639
767640
767641
767642
767643
767644
767645
767646
767647
767648
767649
767650
767651
767652
767653
767654
767655
767656
767657
767658
767659
767660
767661
767662
767663
767664
767665
767666
767667
767668
767669
767670
767671
767672
767673
767674
767675
767676
767677
767678
767679
767680
767681
767682
767683
767684
767685
767686
767687
767688
767689
767690
767691
767692
767693
767694
767695
767696
767697
767698
767699
767700
767701
767702
767703
767704
767705
767706
767707
767708
767709
767710
767711
767712
767713
767714
767715
767716
767717
767718
767719
767720
767721
767722
767723
767724
767725
767726
767727
767728
767729
767730
767731
767732
767733
767734
767735
767736
767737
767738
767739
767740
767741
767742
767743
767744
767745
767746
767747
767748
767749
767750
767751
767752
767753
767754
767755
767756
767757
767758
767759
767760
767761
767762
767763
767764
767765
767766
767767
767768
767769
767770
767771
767772
767773
767774
767775
767776
767777
767778
767779
767780
767781
767782
767783
767784
767785
767786
767787
767788
767789
767790
767791
767792
767793
767794
767795
767796
767797
767798
767799
767800
767801
767802
767803
767804
767805
767806
767807
767808
767809
767810
767811
767812
767813
767814
767815
767816
767817
767818
767819
767820
767821
767822
767823
767824
767825
767826
767827
767828
767829
767830
767831
767832
767833
767834
767835
767836
767837
767838
767839
767840
767841
767842
767843
767844
767845
767846
767847
767848
767849
767850
767851
767852
767853
767854
767855
767856
767857
767858
767859
767860
767861
767862
767863
767864
767865
767866
767867
767868
767869
767870
767871
767872
767873
767874
767875
767876
767877
767878
767879
767880
767881
767882
767883
767884
767885
767886
767887
767888
767889
767890
767891
767892
767893
767894
767895
767896
767897
767898
767899
767900
767901
767902
767903
767904
767905
767906
767907
767908
767909
767910
767911
767912
767913
767914
767915
767916
767917
767918
767919
767920
767921
767922
767923
767924
767925
767926
767927
767928
767929
767930
767931
767932
767933
767934
767935
767936
767937
767938
767939
767940
767941
767942
767943
767944
767945
767946
767947
767948
767949
767950
767951
767952
767953
767954
767955
767956
767957
767958
767959
767960
767961
767962
767963
767964
767965
767966
767967
767968
767969
767970
767971
767972
767973
767974
767975
767976
767977
767978
767979
767980
767981
767982
767983
767984
767985
767986
767987
767988
767989
767990
767991
767992
767993
767994
767995
767996
767997
767998
767999
768000
768001
768002
768003
768004
768005
768006
768007
768008
768009
768010
768011
768012
768013
768014
768015
768016
768017
768018
768019
768020
768021
768022
768023
768024
768025
768026
768027
768028
768029
768030
768031
768032
768033
768034
768035
768036
768037
768038
768039
768040
768041
768042
768043
768044
768045
768046
768047
768048
768049
768050
768051
768052
768053
768054
768055
768056
768057
768058
768059
768060
768061
768062
768063
768064
768065
768066
768067
768068
768069
768070
768071
768072
768073
768074
768075
768076
768077
768078
768079
768080
768081
768082
768083
768084
768085
768086
768087
768088
768089
768090
768091
768092
768093
768094
768095
768096
768097
768098
768099
768100
768101
768102
768103
768104
768105
768106
768107
768108
768109
768110
768111
768112
768113
768114
768115
768116
768117
768118
768119
768120
768121
768122
768123
768124
768125
768126
768127
768128
768129
768130
768131
768132
768133
768134
768135
768136
768137
768138
768139
768140
768141
768142
768143
768144
768145
768146
768147
768148
768149
768150
768151
768152
768153
768154
768155
768156
768157
768158
768159
768160
768161
768162
768163
768164
768165
768166
768167
768168
768169
768170
768171
768172
768173
768174
768175
768176
768177
768178
768179
768180
768181
768182
768183
768184
768185
768186
768187
768188
768189
768190
768191
768192
768193
768194
768195
768196
768197
768198
768199
768200
768201
768202
768203
768204
768205
768206
768207
768208
768209
768210
768211
768212
768213
768214
768215
768216
768217
768218
768219
768220
768221
768222
768223
768224
768225
768226
768227
768228
768229
768230
768231
768232
768233
768234
768235
768236
768237
768238
768239
768240
768241
768242
768243
768244
768245
768246
768247
768248
768249
768250
768251
768252
768253
768254
768255
768256
768257
768258
768259
768260
768261
768262
768263
768264
768265
768266
768267
768268
768269
768270
768271
768272
768273
768274
768275
768276
768277
768278
768279
768280
768281
768282
768283
768284
768285
768286
768287
768288
768289
768290
768291
768292
768293
768294
768295
768296
768297
768298
768299
768300
768301
768302
768303
768304
768305
768306
768307
768308
768309
768310
768311
768312
768313
768314
768315
768316
768317
768318
768319
768320
768321
768322
768323
768324
768325
768326
768327
768328
768329
768330
768331
768332
768333
768334
768335
768336
768337
768338
768339
768340
768341
768342
768343
768344
768345
768346
768347
768348
768349
768350
768351
768352
768353
768354
768355
768356
768357
768358
768359
768360
768361
768362
768363
768364
768365
768366
768367
768368
768369
768370
768371
768372
768373
768374
768375
768376
768377
768378
768379
768380
768381
768382
768383
768384
768385
768386
768387
768388
768389
768390
768391
768392
768393
768394
768395
768396
768397
768398
768399
768400
768401
768402
768403
768404
768405
768406
768407
768408
768409
768410
768411
768412
768413
768414
768415
768416
768417
768418
768419
768420
768421
768422
768423
768424
768425
768426
768427
768428
768429
768430
768431
768432
768433
768434
768435
768436
768437
768438
768439
768440
768441
768442
768443
768444
768445
768446
768447
768448
768449
768450
768451
768452
768453
768454
768455
768456
768457
768458
768459
768460
768461
768462
768463
768464
768465
768466
768467
768468
768469
768470
768471
768472
768473
768474
768475
768476
768477
768478
768479
768480
768481
768482
768483
768484
768485
768486
768487
768488
768489
768490
768491
768492
768493
768494
768495
768496
768497
768498
768499
768500
768501
768502
768503
768504
768505
768506
768507
768508
768509
768510
768511
768512
768513
768514
768515
768516
768517
768518
768519
768520
768521
768522
768523
768524
768525
768526
768527
768528
768529
768530
768531
768532
768533
768534
768535
768536
768537
768538
768539
768540
768541
768542
768543
768544
768545
768546
768547
768548
768549
768550
768551
768552
768553
768554
768555
768556
768557
768558
768559
768560
768561
768562
768563
768564
768565
768566
768567
768568
768569
768570
768571
768572
768573
768574
768575
768576
768577
768578
768579
768580
768581
768582
768583
768584
768585
768586
768587
768588
768589
768590
768591
768592
768593
768594
768595
768596
768597
768598
768599
768600
768601
768602
768603
768604
768605
768606
768607
768608
768609
768610
768611
768612
768613
768614
768615
768616
768617
768618
768619
768620
768621
768622
768623
768624
768625
768626
768627
768628
768629
768630
768631
768632
768633
768634
768635
768636
768637
768638
768639
768640
768641
768642
768643
768644
768645
768646
768647
768648
768649
768650
768651
768652
768653
768654
768655
768656
768657
768658
768659
768660
768661
768662
768663
768664
768665
768666
768667
768668
768669
768670
768671
768672
768673
768674
768675
768676
768677
768678
768679
768680
768681
768682
768683
768684
768685
768686
768687
768688
768689
768690
768691
768692
768693
768694
768695
768696
768697
768698
768699
768700
768701
768702
768703
768704
768705
768706
768707
768708
768709
768710
768711
768712
768713
768714
768715
768716
768717
768718
768719
768720
768721
768722
768723
768724
768725
768726
768727
768728
768729
768730
768731
768732
768733
768734
768735
768736
768737
768738
768739
768740
768741
768742
768743
768744
768745
768746
768747
768748
768749
768750
768751
768752
768753
768754
768755
768756
768757
768758
768759
768760
768761
768762
768763
768764
768765
768766
768767
768768
768769
768770
768771
768772
768773
768774
768775
768776
768777
768778
768779
768780
768781
768782
768783
768784
768785
768786
768787
768788
768789
768790
768791
768792
768793
768794
768795
768796
768797
768798
768799
768800
768801
768802
768803
768804
768805
768806
768807
768808
768809
768810
768811
768812
768813
768814
768815
768816
768817
768818
768819
768820
768821
768822
768823
768824
768825
768826
768827
768828
768829
768830
768831
768832
768833
768834
768835
768836
768837
768838
768839
768840
768841
768842
768843
768844
768845
768846
768847
768848
768849
768850
768851
768852
768853
768854
768855
768856
768857
768858
768859
768860
768861
768862
768863
768864
768865
768866
768867
768868
768869
768870
768871
768872
768873
768874
768875
768876
768877
768878
768879
768880
768881
768882
768883
768884
768885
768886
768887
768888
768889
768890
768891
768892
768893
768894
768895
768896
768897
768898
768899
768900
768901
768902
768903
768904
768905
768906
768907
768908
768909
768910
768911
768912
768913
768914
768915
768916
768917
768918
768919
768920
768921
768922
768923
768924
768925
768926
768927
768928
768929
768930
768931
768932
768933
768934
768935
768936
768937
768938
768939
768940
768941
768942
768943
768944
768945
768946
768947
768948
768949
768950
768951
768952
768953
768954
768955
768956
768957
768958
768959
768960
768961
768962
768963
768964
768965
768966
768967
768968
768969
768970
768971
768972
768973
768974
768975
768976
768977
768978
768979
768980
768981
768982
768983
768984
768985
768986
768987
768988
768989
768990
768991
768992
768993
768994
768995
768996
768997
768998
768999
769000
769001
769002
769003
769004
769005
769006
769007
769008
769009
769010
769011
769012
769013
769014
769015
769016
769017
769018
769019
769020
769021
769022
769023
769024
769025
769026
769027
769028
769029
769030
769031
769032
769033
769034
769035
769036
769037
769038
769039
769040
769041
769042
769043
769044
769045
769046
769047
769048
769049
769050
769051
769052
769053
769054
769055
769056
769057
769058
769059
769060
769061
769062
769063
769064
769065
769066
769067
769068
769069
769070
769071
769072
769073
769074
769075
769076
769077
769078
769079
769080
769081
769082
769083
769084
769085
769086
769087
769088
769089
769090
769091
769092
769093
769094
769095
769096
769097
769098
769099
769100
769101
769102
769103
769104
769105
769106
769107
769108
769109
769110
769111
769112
769113
769114
769115
769116
769117
769118
769119
769120
769121
769122
769123
769124
769125
769126
769127
769128
769129
769130
769131
769132
769133
769134
769135
769136
769137
769138
769139
769140
769141
769142
769143
769144
769145
769146
769147
769148
769149
769150
769151
769152
769153
769154
769155
769156
769157
769158
769159
769160
769161
769162
769163
769164
769165
769166
769167
769168
769169
769170
769171
769172
769173
769174
769175
769176
769177
769178
769179
769180
769181
769182
769183
769184
769185
769186
769187
769188
769189
769190
769191
769192
769193
769194
769195
769196
769197
769198
769199
769200
769201
769202
769203
769204
769205
769206
769207
769208
769209
769210
769211
769212
769213
769214
769215
769216
769217
769218
769219
769220
769221
769222
769223
769224
769225
769226
769227
769228
769229
769230
769231
769232
769233
769234
769235
769236
769237
769238
769239
769240
769241
769242
769243
769244
769245
769246
769247
769248
769249
769250
769251
769252
769253
769254
769255
769256
769257
769258
769259
769260
769261
769262
769263
769264
769265
769266
769267
769268
769269
769270
769271
769272
769273
769274
769275
769276
769277
769278
769279
769280
769281
769282
769283
769284
769285
769286
769287
769288
769289
769290
769291
769292
769293
769294
769295
769296
769297
769298
769299
769300
769301
769302
769303
769304
769305
769306
769307
769308
769309
769310
769311
769312
769313
769314
769315
769316
769317
769318
769319
769320
769321
769322
769323
769324
769325
769326
769327
769328
769329
769330
769331
769332
769333
769334
769335
769336
769337
769338
769339
769340
769341
769342
769343
769344
769345
769346
769347
769348
769349
769350
769351
769352
769353
769354
769355
769356
769357
769358
769359
769360
769361
769362
769363
769364
769365
769366
769367
769368
769369
769370
769371
769372
769373
769374
769375
769376
769377
769378
769379
769380
769381
769382
769383
769384
769385
769386
769387
769388
769389
769390
769391
769392
769393
769394
769395
769396
769397
769398
769399
769400
769401
769402
769403
769404
769405
769406
769407
769408
769409
769410
769411
769412
769413
769414
769415
769416
769417
769418
769419
769420
769421
769422
769423
769424
769425
769426
769427
769428
769429
769430
769431
769432
769433
769434
769435
769436
769437
769438
769439
769440
769441
769442
769443
769444
769445
769446
769447
769448
769449
769450
769451
769452
769453
769454
769455
769456
769457
769458
769459
769460
769461
769462
769463
769464
769465
769466
769467
769468
769469
769470
769471
769472
769473
769474
769475
769476
769477
769478
769479
769480
769481
769482
769483
769484
769485
769486
769487
769488
769489
769490
769491
769492
769493
769494
769495
769496
769497
769498
769499
769500
769501
769502
769503
769504
769505
769506
769507
769508
769509
769510
769511
769512
769513
769514
769515
769516
769517
769518
769519
769520
769521
769522
769523
769524
769525
769526
769527
769528
769529
769530
769531
769532
769533
769534
769535
769536
769537
769538
769539
769540
769541
769542
769543
769544
769545
769546
769547
769548
769549
769550
769551
769552
769553
769554
769555
769556
769557
769558
769559
769560
769561
769562
769563
769564
769565
769566
769567
769568
769569
769570
769571
769572
769573
769574
769575
769576
769577
769578
769579
769580
769581
769582
769583
769584
769585
769586
769587
769588
769589
769590
769591
769592
769593
769594
769595
769596
769597
769598
769599
769600
769601
769602
769603
769604
769605
769606
769607
769608
769609
769610
769611
769612
769613
769614
769615
769616
769617
769618
769619
769620
769621
769622
769623
769624
769625
769626
769627
769628
769629
769630
769631
769632
769633
769634
769635
769636
769637
769638
769639
769640
769641
769642
769643
769644
769645
769646
769647
769648
769649
769650
769651
769652
769653
769654
769655
769656
769657
769658
769659
769660
769661
769662
769663
769664
769665
769666
769667
769668
769669
769670
769671
769672
769673
769674
769675
769676
769677
769678
769679
769680
769681
769682
769683
769684
769685
769686
769687
769688
769689
769690
769691
769692
769693
769694
769695
769696
769697
769698
769699
769700
769701
769702
769703
769704
769705
769706
769707
769708
769709
769710
769711
769712
769713
769714
769715
769716
769717
769718
769719
769720
769721
769722
769723
769724
769725
769726
769727
769728
769729
769730
769731
769732
769733
769734
769735
769736
769737
769738
769739
769740
769741
769742
769743
769744
769745
769746
769747
769748
769749
769750
769751
769752
769753
769754
769755
769756
769757
769758
769759
769760
769761
769762
769763
769764
769765
769766
769767
769768
769769
769770
769771
769772
769773
769774
769775
769776
769777
769778
769779
769780
769781
769782
769783
769784
769785
769786
769787
769788
769789
769790
769791
769792
769793
769794
769795
769796
769797
769798
769799
769800
769801
769802
769803
769804
769805
769806
769807
769808
769809
769810
769811
769812
769813
769814
769815
769816
769817
769818
769819
769820
769821
769822
769823
769824
769825
769826
769827
769828
769829
769830
769831
769832
769833
769834
769835
769836
769837
769838
769839
769840
769841
769842
769843
769844
769845
769846
769847
769848
769849
769850
769851
769852
769853
769854
769855
769856
769857
769858
769859
769860
769861
769862
769863
769864
769865
769866
769867
769868
769869
769870
769871
769872
769873
769874
769875
769876
769877
769878
769879
769880
769881
769882
769883
769884
769885
769886
769887
769888
769889
769890
769891
769892
769893
769894
769895
769896
769897
769898
769899
769900
769901
769902
769903
769904
769905
769906
769907
769908
769909
769910
769911
769912
769913
769914
769915
769916
769917
769918
769919
769920
769921
769922
769923
769924
769925
769926
769927
769928
769929
769930
769931
769932
769933
769934
769935
769936
769937
769938
769939
769940
769941
769942
769943
769944
769945
769946
769947
769948
769949
769950
769951
769952
769953
769954
769955
769956
769957
769958
769959
769960
769961
769962
769963
769964
769965
769966
769967
769968
769969
769970
769971
769972
769973
769974
769975
769976
769977
769978
769979
769980
769981
769982
769983
769984
769985
769986
769987
769988
769989
769990
769991
769992
769993
769994
769995
769996
769997
769998
769999
770000
770001
770002
770003
770004
770005
770006
770007
770008
770009
770010
770011
770012
770013
770014
770015
770016
770017
770018
770019
770020
770021
770022
770023
770024
770025
770026
770027
770028
770029
770030
770031
770032
770033
770034
770035
770036
770037
770038
770039
770040
770041
770042
770043
770044
770045
770046
770047
770048
770049
770050
770051
770052
770053
770054
770055
770056
770057
770058
770059
770060
770061
770062
770063
770064
770065
770066
770067
770068
770069
770070
770071
770072
770073
770074
770075
770076
770077
770078
770079
770080
770081
770082
770083
770084
770085
770086
770087
770088
770089
770090
770091
770092
770093
770094
770095
770096
770097
770098
770099
770100
770101
770102
770103
770104
770105
770106
770107
770108
770109
770110
770111
770112
770113
770114
770115
770116
770117
770118
770119
770120
770121
770122
770123
770124
770125
770126
770127
770128
770129
770130
770131
770132
770133
770134
770135
770136
770137
770138
770139
770140
770141
770142
770143
770144
770145
770146
770147
770148
770149
770150
770151
770152
770153
770154
770155
770156
770157
770158
770159
770160
770161
770162
770163
770164
770165
770166
770167
770168
770169
770170
770171
770172
770173
770174
770175
770176
770177
770178
770179
770180
770181
770182
770183
770184
770185
770186
770187
770188
770189
770190
770191
770192
770193
770194
770195
770196
770197
770198
770199
770200
770201
770202
770203
770204
770205
770206
770207
770208
770209
770210
770211
770212
770213
770214
770215
770216
770217
770218
770219
770220
770221
770222
770223
770224
770225
770226
770227
770228
770229
770230
770231
770232
770233
770234
770235
770236
770237
770238
770239
770240
770241
770242
770243
770244
770245
770246
770247
770248
770249
770250
770251
770252
770253
770254
770255
770256
770257
770258
770259
770260
770261
770262
770263
770264
770265
770266
770267
770268
770269
770270
770271
770272
770273
770274
770275
770276
770277
770278
770279
770280
770281
770282
770283
770284
770285
770286
770287
770288
770289
770290
770291
770292
770293
770294
770295
770296
770297
770298
770299
770300
770301
770302
770303
770304
770305
770306
770307
770308
770309
770310
770311
770312
770313
770314
770315
770316
770317
770318
770319
770320
770321
770322
770323
770324
770325
770326
770327
770328
770329
770330
770331
770332
770333
770334
770335
770336
770337

KeyboardInterrupt:

In [ ]:
# prompt: building.csv 열어줘

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/building_daegu.csv')
len(df.iloc[0])

<ipython-input-10-3c3816be5b56>:5: DtypeWarning: Columns (14,15,60,61) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/building_daegu.csv')

78

In [ ]:
print(df.shape[0])

281541

In [ ]:
# prompt: column  다보여줘
44 45 60 75
df_03.columns

Index(['대지위치', '시군구코드', '법정동코드', '대지구분코드', '번', '지', '관리건축물대장PK', '대장구분코드',
       '대장구분코드명', '대장종류코드', '대장종류코드명', '도로명대지위치', '건물명', '특수지명', '블록', '로트',
       '외필지수', '새주소도로코드', '새주소법정동코드', '새주소지상지하코드', '새주소본번', '새주소부번', '동명칭',
       '주부속구분코드', '주부속구분코드명', '대지면적(㎡)', '건축면적(㎡)', '건폐율(%)', '연면적(㎡)',
       '용적률산정연면적(㎡)', '용적률(%)', '구조코드', '구조코드명', '기타구조', '주용도코드', '주용도코드명',
       '기타용동', '지붕코드', '지붕코드명', '기타지붕', '세대수(세대)', '가구수(가구)', '높이(m)', '지상층수',
       '지하층수', '승용승강기수', '비상용승강기수', '부속건축물수', '부속건축물면적(㎡)', '총동연면적(㎡)',
       '옥내기계식대수(대)', '옥내기계식면적(㎡)', '옥외기계식대수(대)', '옥외기계식면적(㎡)', '옥내자주식면적(㎡)',
       '옥외자주식대수(대)', '옥외자주식면적(㎡)', '허가일', '착공일', '사용승인일', '허가번호년',
       '옥내자주식대수(대)', '허가번호기관코드', '허가번호기관코드명', '허가번호구분코드', '허가번호구분코드명', '호수(호)',
       '에너지효율등급', '에너지절감률', 'EPI점수', '친환경건축물등급', '친환경건축물인증점수', '지능형건축물등급',
       '지능형건축물인증점수', '생성일자', '내진설계적용여부', '내진능력'],
      dtype='object')

In [ ]:
# prompt: /content/building_daegu.csv 열어줘

print(len(df))
df

281539

,관리건축물대장PK,대장구분코드,대장구분코드명,대장종류코드,대장종류코드명,지번주소명,도로명대지위치,건물명,시군구코드,법정동코드,...,에너지절감률,EPI점수,친환경건축물등급,친환경건축물인증점수,지능형건축물등급,지능형건축물인증점수,생성일자,내진설계적용유무,내진능력,PNU
0,12381766,1,일반,2,일반건축물,대구광역시 군위군 군위읍 동부리 409-1번지,대구광역시 군위군 동서5길 5-10 (군위읍 동부리),NaN,27720,25021,...,0.0,0.0,NaN,0.0,NaN,0,20221126,0.0,NaN,2772025021004090001
1,123811406,1,일반,2,일반건축물,대구광역시 군위군 군위읍 서부리 22-1번지,NaN,NaN,27720,25022,...,0.0,0.0,NaN,0.0,NaN,0,20221126,0.0,NaN,2772025022000220001
2,123811737,1,일반,2,일반건축물,대구광역시 군위군 군위읍 서부리 196번지,대구광역시 군위군 중앙3길 19-11 (군위읍 서부리),NaN,27720,25022,...,0.0,0.0,NaN,0.0,NaN,0,20221126,0.0,NaN,2772025022001960000
3,123811868,1,일반,2,일반건축물,대구광역시 군위군 군위읍 서부리 281번지,대구광역시 군위군 중앙3길 5-13 (군위읍 서부리),NaN,27720,25022,...,0.0,0.0,NaN,0.0,NaN,0,20221126,0.0,NaN,2772025022002810000
4,123812028,1,일반,2,일반건축물,대구광역시 군위군 군위읍 서부리 395-4번지,대구광역시 군위군 중앙4길 19 (군위읍 서부리),중앙선교원어린이집,27720,25022,...,0.0,0.0,NaN,0.0,NaN,0,20221126,0.0,NaN,2772025022003950004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281534,1047118244,2,집합,3,표제부,대구광역시 서구 비산동 698-10번지,대구광역시 서구 북비산로61길 42-16 (비산동),NaN,27170,10200,...,0.0,0.0,NaN,0.0,NaN,0,20221126,0.0,NaN,2717010200006980010
281535,10471100186041,2,집합,3,표제부,대구광역시 서구 평리동 1680번지,대구광역시 서구 국채보상로50길 20 (평리동),평리 푸르지오,27170,10300,...,0.0,60.7,NaN,0.0,NaN,0,20221126,0.0,NaN,2717010300016800000
281536,1050132365,2,집합,3,표제부,대구광역시 수성구 범물동 1328번지,대구광역시 수성구 지범로40길 11 (범물동),범물서한화성아파트,27260,11300,...,0.0,0.0,NaN,0.0,NaN,0,20221126,1.0,NaN,2726011300013280000
281537,1049127992,2,집합,3,표제부,대구광역시 북구 동변동 682번지,대구광역시 북구 동변로 24 (동변동),유니버시아드선수촌,27230,11400,...,0.0,0.0,NaN,0.0,NaN,0,20221126,0.0,NaN,2723011400006820000
281538,10511100191308,2,집합,3,표제부,대구광역시 달서구 성당동 839번지,대구광역시 달서구 장기로 145 (성당동),성당 래미안 e-편한세상,27290,10100,...,0.0,66.2,NaN,0.0,NaN,0,20221126,1.0,NaN,2729010100008390000

In [ ]:
import pandas as pd
# df = pd.read_csv('/content/building_daegu.csv')

# df = pd.read_csv("/content/drive/MyDrive/building.csv")

# df["col_5_6_7"] = df.iloc[:, 4].astype(str) + "_" + df.iloc[:, 5].astype(str) + "_" + df.iloc[:, 6].astype(str)
df["지번주소"] = df.iloc[:, 5].astype(str)
df["도로명주소"] = df.iloc[:, 6].astype(str)
df["면적"] = df.iloc[:, 26].astype(str)
df["용도"] = df.iloc[:, 35].astype(str)

df["지상층수"] = df.iloc[:, 43].astype(str)
df["지하층수"] = df.iloc[:, 44].astype(str)
df["사용승인일"] = df.iloc[:, 60].astype(str)
df["착공일"] = df.iloc[:, 59].astype(str)

import re
# df["pnu"] = df.iloc[:, 8:13].astype(str).agg("".join, axis=1)
df["pnu"] = df.iloc[:, 8:13].astype(str).replace("\.", "", regex=True).agg("".join, axis=1)
# df["pnu"] = df["pnu"].str[:10]


# df_selected = df.iloc[:, [28, 35]].copy()
# df_selected.columns = ["면적", "용도"]

# df_final = df_selected.copy()
# df_final["지번주소"] = df["지번주소"]
# df_final["도로명주소"] = df["도로명주소"]
# df_final["pnu"] = df["pnu"]
# df_final["지상층수"] = df["지상층수"]
# df_final["지하층수"] = df["지하층수"]
# df_final["사용승인일"] = df["사용승인일"]
# df_final["착공일"] = df["착공일"]

# # 저장
# df_final.to_csv("reduced_columns.csv", index=False)

save_cols = ["pnu", "지번주소", "도로명주소", "지상층수", "지하층수", "사용승인일", "착공일","면적","용도"]
building = df[save_cols]
df[save_cols].to_csv("last.csv", index=False, encoding="utf-8-sig")
print("완료! 최종 파일은 'reduced_columns.csv'로 저장됐습니다.")

완료! 최종 파일은 'reduced_columns.csv'로 저장됐습니다.

In [ ]:
 df

,관리건축물대장PK,대장구분코드,대장구분코드명,대장종류코드,대장종류코드명,지번주소명,도로명대지위치,건물명,시군구코드,법정동코드,...,지능형건축물인증점수,생성일자,내진설계적용유무,내진능력,PNU,지번주소,도로명주소,면적,용도,pnu
0,12381766,1,일반,2,일반건축물,대구광역시 군위군 군위읍 동부리 409-1번지,대구광역시 군위군 동서5길 5-10 (군위읍 동부리),NaN,27720,25021,...,0,20221126,0.0,NaN,2772025021004090001,대구광역시 군위군 군위읍 동부리 409-1번지,대구광역시 군위군 동서5길 5-10 (군위읍 동부리),22.68,단독주택,277202502104091
1,123811406,1,일반,2,일반건축물,대구광역시 군위군 군위읍 서부리 22-1번지,NaN,NaN,27720,25022,...,0,20221126,0.0,NaN,2772025022000220001,대구광역시 군위군 군위읍 서부리 22-1번지,nan,189.72,제1종근린생활시설,27720250220221
2,123811737,1,일반,2,일반건축물,대구광역시 군위군 군위읍 서부리 196번지,대구광역시 군위군 중앙3길 19-11 (군위읍 서부리),NaN,27720,25022,...,0,20221126,0.0,NaN,2772025022001960000,대구광역시 군위군 군위읍 서부리 196번지,대구광역시 군위군 중앙3길 19-11 (군위읍 서부리),95.18,단독주택,277202502201960
3,123811868,1,일반,2,일반건축물,대구광역시 군위군 군위읍 서부리 281번지,대구광역시 군위군 중앙3길 5-13 (군위읍 서부리),NaN,27720,25022,...,0,20221126,0.0,NaN,2772025022002810000,대구광역시 군위군 군위읍 서부리 281번지,대구광역시 군위군 중앙3길 5-13 (군위읍 서부리),56.8,단독주택,277202502202810
4,123812028,1,일반,2,일반건축물,대구광역시 군위군 군위읍 서부리 395-4번지,대구광역시 군위군 중앙4길 19 (군위읍 서부리),중앙선교원어린이집,27720,25022,...,0,20221126,0.0,NaN,2772025022003950004,대구광역시 군위군 군위읍 서부리 395-4번지,대구광역시 군위군 중앙4길 19 (군위읍 서부리),198.9,노유자시설,277202502203954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281534,1047118244,2,집합,3,표제부,대구광역시 서구 비산동 698-10번지,대구광역시 서구 북비산로61길 42-16 (비산동),NaN,27170,10200,...,0,20221126,0.0,NaN,2717010200006980010,대구광역시 서구 비산동 698-10번지,대구광역시 서구 북비산로61길 42-16 (비산동),55.63,공동주택,2717010200069810
281535,10471100186041,2,집합,3,표제부,대구광역시 서구 평리동 1680번지,대구광역시 서구 국채보상로50길 20 (평리동),평리 푸르지오,27170,10300,...,0,20221126,0.0,NaN,2717010300016800000,대구광역시 서구 평리동 1680번지,대구광역시 서구 국채보상로50길 20 (평리동),12.24,공동주택,2717010300016800
281536,1050132365,2,집합,3,표제부,대구광역시 수성구 범물동 1328번지,대구광역시 수성구 지범로40길 11 (범물동),범물서한화성아파트,27260,11300,...,0,20221126,1.0,NaN,2726011300013280000,대구광역시 수성구 범물동 1328번지,대구광역시 수성구 지범로40길 11 (범물동),5760.38,공동주택,2726011300013280
281537,1049127992,2,집합,3,표제부,대구광역시 북구 동변동 682번지,대구광역시 북구 동변로 24 (동변동),유니버시아드선수촌,27230,11400,...,0,20221126,0.0,NaN,2723011400006820000,대구광역시 북구 동변동 682번지,대구광역시 북구 동변로 24 (동변동),29.8556,공동주택,272301140006820
281538,10511100191308,2,집합,3,표제부,대구광역시 달서구 성당동 839번지,대구광역시 달서구 장기로 145 (성당동),성당 래미안 e-편한세상,27290,10100,...,0,20221126,1.0,NaN,2729010100008390000,대구광역시 달서구 성당동 839번지,대구광역시 달서구 장기로 145 (성당동),1042.85,공동주택,272901010008390

In [ ]:
building = df

In [ ]:
# prompt: processed_building_data.csv 열어줘
building.to_csv('building2.csv')

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# prompt: /content/남구.csv 이것좀 열어줘

import pandas as pd

n = pd.read_csv('/content/drive/MyDrive/전기/남구2024.csv')

ds = pd.read_csv('/content/drive/MyDrive/전기/달서구2024.csv')
dsg = pd.read_csv('/content/drive/MyDrive/전기/달성군2024.csv')
d = pd.read_csv('/content/drive/MyDrive/전기/동구2024.csv')
b = pd.read_csv('/content/drive/MyDrive/전기/북구2024.csv')
s = pd.read_csv('/content/drive/MyDrive/전기/서구2024.csv')
ss = pd.read_csv('/content/drive/MyDrive/전기/수성구2024.csv')
j = pd.read_csv('/content/drive/MyDrive/전기/중구2024.csv')

In [ ]:
# df = pd.concat([n, ds, dsg, d, b, s, ss, j], axis=1)
# df_all = pd.concat([df1, df2, df3], axis=0, ignore_index=True)
df = pd.concat([n, ds, dsg, d, b, s, ss, j], axis=0, ignore_index=True)

In [ ]:
print(n.shape[1])
print(ds.shape[1])
print(dsg.shape[1])
print(d.shape[1])
print(b.shape[1])
print(s.shape[1])
print(ss.shape[1])
print(j.shape[1])

14
14
14
14
14
14
14
14

In [ ]:
# df["PNU"] = df[["시군구코드", "법정동코드", "대지구분코드", "번", "지"]].astype(str).replace("\.", "", regex=True).agg("".join, axis=1)
df["pnu"] = df[["시군구코드", "법정동코드", "대지구분코드","번","지"]].astype(str).replace("\.", "", regex=True).agg("".join, axis=1)
# df["pnu"] = df["pnu"].str[:10]
# df["pnu"] = df["pnu"].str[:-1]

In [ ]:
df
# df["PNU"] = df[["시군구코드", "법정동코드", "대지구분코드", "번", "지"]].astype(str).replace("\.", "", regex=True).agg("".join, axis=1)

,대지위치,시군구코드,법정동코드,대지구분코드,번,지,사용년월,도로명대지위치,새주소일련번호,새주소도로코드,새주소지상지하코드,새주소본번,새주소부번,사용량(KWh),pnu
0,대구광역시 남구 이천동 121-70,27200,10100,0,121,70,202401,대구광역시 남구 명덕로68길 지상 79 (이천동),1,2.720042e+11,0.0,79.0,0.0,180038,2720010100012170
1,대구광역시 남구 이천동 121-70,27200,10100,0,121,70,202402,대구광역시 남구 명덕로68길 지상 77 (이천동),1,2.720042e+11,0.0,77.0,0.0,181483,2720010100012170
2,대구광역시 남구 이천동 121-70,27200,10100,0,121,70,202403,대구광역시 남구 명덕로68길 지상 77 (이천동),1,2.720042e+11,0.0,77.0,0.0,163726,2720010100012170
3,대구광역시 남구 이천동 121-70,27200,10100,0,121,70,202404,대구광역시 남구 명덕로68길 지상 79 (이천동),1,2.720042e+11,0.0,79.0,0.0,165443,2720010100012170
4,대구광역시 남구 이천동 121-70,27200,10100,0,121,70,202405,대구광역시 남구 명덕로68길 지상 77 (이천동),1,2.720042e+11,0.0,77.0,0.0,151984,2720010100012170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643186,대구광역시 중구 대봉동 777,27110,15700,0,777,0,202408,대구광역시 중구 대봉로 지상 240 (대봉동),1,2.711031e+11,0.0,240.0,0.0,5861,271101570007770
643187,대구광역시 중구 대봉동 777,27110,15700,0,777,0,202409,대구광역시 중구 대봉로 240 (대봉동),1,2.711031e+11,0.0,240.0,0.0,5863,271101570007770
643188,대구광역시 중구 대봉동 777,27110,15700,0,777,0,202410,대구광역시 중구 대봉로 240 (대봉동),1,2.711031e+11,0.0,240.0,0.0,5799,271101570007770
643189,대구광역시 중구 대봉동 777,27110,15700,0,777,0,202411,대구광역시 중구 대봉로 240 (대봉동),1,2.711031e+11,0.0,240.0,0.0,5825,271101570007770
643190,대구광역시 중구 대봉동 777,27110,15700,0,777,0,202412,대구광역시 중구 대봉로 240 (대봉동),1,2.711031e+11,0.0,240.0,0.0,5770,271101570007770

In [ ]:

df.drop(columns=["시군구코드", "법정동코드", "대지구분코드", "번", "지", "새주소지상지하코드",'새주소본번','새주소부번'], inplace=True)
df.drop(columns=['새주소도로코드','새주소일련번호'], inplace=True)
df.rename(columns={"대지위치": "지번주소"}, inplace=True)
df.rename(columns={"도로명대지위치": "도로명주소"}, inplace=True)
df.rename(columns={"사용량(KWh)": "전기사용량"}, inplace=True)

In [ ]:
# prompt: df to elec24.csv로

df.to_csv('elec24.csv', index=False)

In [ ]:
# prompt: /content/남구.csv 이것좀 열어줘

import pandas as pd

n = pd.read_csv('/content/drive/MyDrive/전기/남구2023.csv')

ds = pd.read_csv('/content/drive/MyDrive/전기/달서구2023.csv')
dsg = pd.read_csv('/content/drive/MyDrive/전기/달성군2023.csv')
d = pd.read_csv('/content/drive/MyDrive/전기/동구2023.csv')
b = pd.read_csv('/content/drive/MyDrive/전기/북구2023.csv')
s = pd.read_csv('/content/drive/MyDrive/전기/서구2023.csv')
ss = pd.read_csv('/content/drive/MyDrive/전기/수성구2023.csv')
j = pd.read_csv('/content/drive/MyDrive/전기/중구2023.csv')

In [ ]:
df23 = pd.concat([n, ds, dsg, d, b, s, ss, j], axis=0, ignore_index=True)

In [ ]:
# df23["pnu"] = df23[["시군구코드", "법정동코드"]].astype(str).replace("\.", "", regex=True).agg("".join, axis=1)
# df23["pnu"] = df23[["시군구코드", "법정동코드", "대지구분코드", "번", "지"]].astype(str).replace("\.", "", regex=True).agg("".join, axis=1)
# df23["pnu"] = df23["pnu"].str[:10]
df23["pnu"] = df23[["시군구코드", "법정동코드", "대지구분코드","번","지"]].astype(str).replace("\.", "", regex=True).agg("".join, axis=1)

df23.drop(columns=["시군구코드", "법정동코드", "대지구분코드", "번", "지", "새주소지상지하코드",'새주소본번','새주소부번'], inplace=True)
df23.drop(columns=['새주소도로코드','새주소일련번호'], inplace=True)
df23.rename(columns={"대지위치": "지번주소"}, inplace=True)
df23.rename(columns={"도로명대지위치": "도로명주소"}, inplace=True)
df23.rename(columns={"사용량(KWh)": "전기사용량"}, inplace=True)
df23

In [ ]:
elec2324 = pd.concat([df, df23], axis=0, ignore_index=True)

In [ ]:
# prompt: ds2324 csv로

elec2324.to_csv('elec2.csv', index=False)

In [ ]:
# prompt: /content/남구.csv 이것좀 열어줘

import pandas as pd

n = pd.read_csv('/content/drive/MyDrive/gas2024/남구2024가스.csv')

ds = pd.read_csv('/content/drive/MyDrive/gas2024/달서구2024가스.csv')
dsg = pd.read_csv('/content/drive/MyDrive/gas2024/달성군2024가스.csv')
d = pd.read_csv('/content/drive/MyDrive/gas2024/동구2024가스.csv')
b = pd.read_csv('/content/drive/MyDrive/gas2024/북구2024가스.csv')
s = pd.read_csv('/content/drive/MyDrive/gas2024/서구2024가스.csv')
ss = pd.read_csv('/content/drive/MyDrive/gas2024/수성구2024가스.csv')
j = pd.read_csv('/content/drive/MyDrive/gas2024/중구2024가스.csv')

In [ ]:
df24 = pd.concat([n, ds, dsg, d, b, s, ss, j], axis=0, ignore_index=True)

In [ ]:
df24["PNU"] = df24[["시군구코드", "법정동코드", "대지구분코드", "번", "지"]].astype(str).replace("\.", "", regex=True).agg("".join, axis=1)
df24.drop(columns=["시군구코드", "법정동코드", "대지구분코드", "번", "지", "새주소지상지하코드",'새주소본번','새주소부번'], inplace=True)
df24.drop(columns=['새주소도로코드','새주소일련번호'], inplace=True)
df24.rename(columns={"대지위치": "지번주소"}, inplace=True)
df24.rename(columns={"도로명대지위치": "도로명주소"}, inplace=True)
df24.rename(columns={"사용량(KWh)": "가스사용량"}, inplace=True)
df24

# df24.to_csv('gas24.csv', index=False)

,지번주소,사용년월,도로명주소,가스사용량,PNU
0,대구광역시 남구 이천동 121-70,202401,대구광역시 남구 명덕로68길 지상 79 (이천동),694234,2720010100012170
1,대구광역시 남구 이천동 121-70,202402,대구광역시 남구 명덕로68길 지상 77 (이천동),779517,2720010100012170
2,대구광역시 남구 이천동 121-70,202403,대구광역시 남구 명덕로68길 지상 79 (이천동),624218,2720010100012170
3,대구광역시 남구 이천동 121-70,202404,대구광역시 남구 명덕로68길 지상 79 (이천동),480474,2720010100012170
4,대구광역시 남구 이천동 121-70,202405,대구광역시 남구 명덕로68길 지상 77 (이천동),219604,2720010100012170
...,...,...,...,...,...
196501,대구광역시 중구 대봉동 758,202411,대구광역시 중구 동덕로 55 (대봉동),112711,271101570007580
196502,대구광역시 중구 대봉동 758,202412,대구광역시 중구 동덕로 55 (대봉동),257619,271101570007580
196503,대구광역시 중구 대봉동 777,202409,대구광역시 중구 대봉로 240 (대봉동),12,271101570007770
196504,대구광역시 중구 대봉동 777,202411,대구광역시 중구 대봉로 240 (대봉동),12,271101570007770
196505,대구광역시 중구 대봉동 777,202412,대구광역시 중구 대봉로 240 (대봉동),141,271101570007770

In [ ]:
df24.to_csv('gas2.csv', index=False)

In [ ]:
import argparse
import copy
import csv
import json
import re
import sqlite3
import traceback
import os
# from vllm import LLM, SamplingParams
# from func_timeout import func_set_timeout
# import func_timeout
import tqdm
def convert_fk_index(data):
    fk_holder = []
    table_names_original = [i.lower() for i in data['table_names_original']]  # some bug
    column_names_original = [(i[0], i[1].lower()) for i in data['column_names_original']]
    for fk in data["foreign_keys"]:
        tn, col, ref_tn, ref_col = fk[0][0], fk[0][1], fk[1][0], fk[1][1]
        if type(tn) is str:
            tn = tn.lower()
        if type(col) is str:
            col = col.lower()
        if type(ref_tn) is str:
            ref_tn = ref_tn.lower()
        if type(ref_col) is str:
            ref_col = ref_col.lower()
        ref_cid, cid = None, None
        try:
            tid = table_names_original.index(tn)
            ref_tid = table_names_original.index(ref_tn)
            for i, (tab_id, col_org) in enumerate(column_names_original):
                if tab_id == ref_tid and ref_col == col_org:
                    ref_cid = i
                elif tid == tab_id and col == col_org:
                    cid = i
            if ref_cid and cid:
                fk_holder.append([cid, ref_cid])
        except:
            traceback.print_exc()
            print("table_names_original: ", table_names_original)
            print("finding tab name: ", tn, ref_tn)
            print(data)
            # sys.exit()
    return fk_holder


def dump_db_json_schema(db, f):
    '''read table and column info'''

    try:
        conn = sqlite3.connect(db)
    except:
        print(db)
        exit()
    conn.execute('pragma foreign_keys=ON')
    cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table';")

    data = {'db_id': f,
            'table_names_original': [],
            'table_names': [],
            'column_names_original': [(-1, '*')],
            'column_names': [(-1, '*')],
            'column_types': ['text'],
            'primary_keys': [],
            'foreign_keys': []}

    fk_holder = []
    for i, item in enumerate(cursor.fetchall()):
        table_name = item[0]
        data['table_names_original'].append(table_name)
        data['table_names'].append(table_name.lower().replace("_", ' '))
        fks = conn.execute("PRAGMA foreign_key_list('{}') ".format(table_name)).fetchall()
        # print("db:{} table:{} fks:{}".format(f,table_name,fks))
        fk_holder.extend([[(table_name, fk[3]), (fk[2], fk[4])] for fk in fks])
        cur = conn.execute("PRAGMA table_info('{}') ".format(table_name))
        for j, col in enumerate(cur.fetchall()):
            data['column_names_original'].append((i, col[1]))
            data['column_names'].append((i, col[1].lower().replace("_", " ")))
            # varchar, '' -> text, int, numeric -> integer,
            col_type = col[2].lower()
            if 'char' in col_type or col_type == '' or 'text' in col_type or 'var' in col_type:
                data['column_types'].append('text')
            elif 'int' in col_type or 'numeric' in col_type or 'decimal' in col_type or 'number' in col_type \
                    or 'id' in col_type or 'real' in col_type or 'double' in col_type or 'float' in col_type:
                data['column_types'].append('number')
            elif 'date' in col_type or 'time' in col_type or 'year' in col_type:
                data['column_types'].append('time')
            elif 'boolean' in col_type:
                data['column_types'].append('boolean')
            else:
                data['column_types'].append('others')

            if col[5] == 1:
                data['primary_keys'].append(len(data['column_names']) - 1)

    data["foreign_keys"] = fk_holder
    data['foreign_keys'] = convert_fk_index(data)

    return data


def get_schema_dict(db, kk=3):
    """
    Get database's schema, which is a dict with table name as key
    and list of column names as value
    :param db: database path
    :return: schema dict
    """
    data = dump_db_json_schema(db, db.split('/')[-1])
    tables = data['table_names_original']
    column_types = data['column_types']
    primary_keys = data['primary_keys']
    foreign_keys = data['foreign_keys']
    column_names = data['column_names_original']

    schema_dict = {
        'tables': {},
        'foreign_keys': []
    }

    for i, table in enumerate(tables):
        t = {}
        for j, c in enumerate(column_names):
            if c[0] == i:
                if j in primary_keys:
                    t[c[1]] = [column_types[j].upper(), True]
                else:
                    t[c[1]] = [column_types[j].upper(), True]
        schema_dict['tables'][table] = t

    for foreign_key in foreign_keys:
        t1 = tables[column_names[foreign_key[0]][0]]
        c1 = column_names[foreign_key[0]][1]
        t2 = tables[column_names[foreign_key[1]][0]]
        c2 = column_names[foreign_key[1]][1]
        schema_dict['foreign_keys'].append([t1, c1, t2, c2])

    conn = sqlite3.connect(db)
    cursor = conn.cursor()
    # get exapmles
    for table in schema_dict['tables'].keys():
        try:
            select_query = f'SELECT * FROM `{table}` LIMIT {kk}'
            cursor.execute(select_query)
            rows = cursor.fetchall()
            cursor.execute(f"PRAGMA table_info(`{table}`);")
            columns = [column[1] for column in cursor.fetchall()]
            for i, c in enumerate(columns):
                cls_valuse = [f"{row[i][0:100]}..." if type(row[i]) is str and len(row[i]) > 100 else row[i] for row in
                              rows]
                schema_dict['tables'][table][c].append(cls_valuse)
        except Exception as e:
            print(e)
    return schema_dict


def get_example_str(schema_dict, k=1):
    tables = list(schema_dict['tables'].keys())
    examples = {}
    for table in tables:
        table_dict = schema_dict['tables'][table]
        example = []
        for cls in table_dict.keys():
            example.append(table_dict[cls][2])
        example_str = []
        for i, v in enumerate(example[0]):
            example_str.append(tuple([e[i] for e in example]))
            if (i + 1) == k:
                break
        examples[table] = example_str

    e_s = ''
    for key in examples.keys():
        e_s += f"{key}: " + str(examples[key]) + '\n'

    return e_s[:-1]


def get_schmea_str_and_examples(schema_dict):
    schmea_str = ""
    tables = list(schema_dict['tables'].keys())
    examples = {}
    for table in tables:
        if ' ' in table:
            table_str = f'CREATE TABLE "{table}" ('
        else:
            table_str = f"CREATE TABLE {table} ("
        table_dict = schema_dict['tables'][table]

        pk_str = ''
        example = []
        for cls in table_dict.keys():
            try:
                cls_ = f'"{cls}"' if ' ' in cls else cls
                table_str += f"{cls_} {table_dict[cls][0]}, "
                if table_dict[cls][1]:
                    pk_str += cls_ + ', '
                example.append(table_dict[cls][2])
            except Exception as e:
                print(e)
        example_str = []

        try:
            for i, v in enumerate(example[0]):
                example_str.append(tuple([e[i] for e in example]))
        except Exception as e:
            print(e)

        examples[table] = example_str

        if pk_str != '':
            table_str += f"PRIMARY KEY({pk_str[:-2]}), "

        fk_str = ''
        for fk in schema_dict['foreign_keys']:
            if fk[0] == table and fk[2] in tables:
                if fk[3] in schema_dict['tables'][fk[2]].keys():
                    fk = [f'"{f}"' if ' ' in f else f for f in fk]
                    fk_str += f'FOREIGN KEY ({fk[1]}) REFERENCES {fk[2]}({fk[3]}), '
        if fk_str != '':
            table_str += fk_str

        schmea_str += table_str[:-2] + '); '

    schmea_str = schmea_str[:-1]

    e_s = ''
    for key in examples.keys():
        e_s += f"{key}: " + str(examples[key]) + '\n'

    return schmea_str, e_s[:-1]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
df_output = pd.read_csv('/content/drive/MyDrive/output.csv')

print(df_output.head())

                                                문제  \
0             대구시에서 연면적이 1만 제곱미터 이상인 건축물의 목록을 보여줘.
1  대구광역시 수성구에 위치한 업무시설 건축물 중 2023년 기준으로 사용 중인 건물은?
2            대구시 동구에 있는 건물 중 난방 방식이 지역난방인 건물만 찾아줘.
3                      대구시 내 지하층이 2개 이상인 건축물을 알려줘.
4                    대구시 북구에서 2022년에 건축된 건물은 몇 개야?

                                           SQL_Query
0  대구시에서 연면적이 1만 제곱미터 이상인 건축물의 목록을 조회하는 SQL 쿼리를 아...
1  대구광역시 수성구에 위치한 업무시설 건축물 중 2023년 기준으로 사용 중인 건물을...
2  대구시 동구에 있는 건물 중 난방 방식이 지역난방인 경우에 대한 SQL 쿼리를 작성...
3  아래는 대구시 내 지하층이 2개 이상인 건축물을 찾기 위한 SQL 쿼리입니다.\n\...
4  대구시 북구에서 2022년에 건축된 건물을 찾기 위한 SQL 쿼리는 다음과 같습니다...

In [ ]:
# prompt: /content/drive/MyDrive/elec2324.csv 열어줘
import pandas as pd
# elec2324 = pd.read_csv('/content/drive/MyDrive/electricity.csv')
elec = pd.read_csv('/content/drive/MyDrive/new/elec3.csv')
# po = pd.read_csv('/content/drive/MyDrive/populate.csv')
po = pd.read_csv('/content/drive/MyDrive/new/po3.csv')
# building = pd.read_csv('/content/drive/MyDrive/building.csv')
building = pd.read_csv('/content/drive/MyDrive/new/building3.csv')
gas = pd.read_csv('/content/drive/MyDrive/new/gas3.csv')

In [ ]:
gas = gas.drop(columns=['Unnamed: 0'])
building = building.drop(columns=['Unnamed: 0'])
elec = elec.drop(columns=['Unnamed: 0'])
po = po.drop(columns=['Unnamed: 0'])

In [ ]:
#시작
from sqlalchemy import create_engine, text, inspect
from sqlalchemy.orm import Session

from sqlalchemy import create_engine

engine = create_engine("sqlite:///database.db")  # 또는 "postgresql://user:password@host/dbname"

with engine.begin() as conn:
    elec.to_sql("electricity", con=conn, if_exists="replace", index=False)
    building.to_sql("building", con=conn, if_exists="replace", index=False)
    po.to_sql("population", con=conn, if_exists="replace", index=False)
    gas.to_sql("gas", con=conn, if_exists="replace", index=False)

In [ ]:
sql_results = []
data_header = [["NLQ", "Predict", "GOLD", 'database']]
prompts = []
db_path = '/content/database.db'
schema_dict = get_schema_dict(db_path)
database_schema, examples = get_schmea_str_and_examples(schema_dict)
schema_dict_ = schema_dict

In [ ]:
database_schema

'CREATE TABLE electricity (지번주소 TEXT, 사용년월 NUMBER, 도로명주소 TEXT, 전기사용량 NUMBER, pnu NUMBER, PRIMARY KEY(지번주소, 사용년월, 도로명주소, 전기사용량, pnu)); CREATE TABLE building (pnu NUMBER, 지번주소 TEXT, 도로명주소 TEXT, 지상층수 NUMBER, 지하층수 NUMBER, 사용승인일 TEXT, 착공일 TEXT, 면적 NUMBER, 용도 TEXT, 법정동코드PNU NUMBER, PRIMARY KEY(pnu, 지번주소, 도로명주소, 지상층수, 지하층수, 사용승인일, 착공일, 면적, 용도, 법정동코드PNU)); CREATE TABLE population (지번주소 TEXT, 2023년_총인구수 TEXT, 2023년_세대수 TEXT, "2023년_세대당 인구" NUMBER, "2023년_남자 인구수" TEXT, "2023년_여자 인구수" TEXT, 2024년_총인구수 TEXT, 2024년_세대수 TEXT, "2024년_세대당 인구" NUMBER, "2024년_남자 인구수" TEXT, "2024년_여자 인구수" TEXT, pnu NUMBER, 법정동코드PNU NUMBER, PRIMARY KEY(지번주소, 2023년_총인구수, 2023년_세대수, "2023년_세대당 인구", "2023년_남자 인구수", "2023년_여자 인구수", 2024년_총인구수, 2024년_세대수, "2024년_세대당 인구", "2024년_남자 인구수", "2024년_여자 인구수", pnu, 법정동코드PNU)); CREATE TABLE gas (지번주소 TEXT, 사용년월 NUMBER, 도로명주소 TEXT, 가스사용량 NUMBER, pnu NUMBER, 법정동코드PNU NUMBER, PRIMARY KEY(지번주소, 사용년월, 도로명주소, 가스사용량, pnu, 법정동코드PNU));'

In [ ]:
examples

"electricity: [('대구광역시 남구 이천동 121-70', 202401, '대구광역시 남구 명덕로68길 지상  79 (이천동) ', 180038, 2720010100012170), ('대구광역시 남구 이천동 121-70', 202402, '대구광역시 남구 명덕로68길 지상  77 (이천동) ', 181483, 2720010100012170), ('대구광역시 남구 이천동 121-70', 202403, '대구광역시 남구 명덕로68길 지상  77 (이천동) ', 163726, 2720010100012170)]\nbuilding: [(277202502104091, '대구광역시 군위군 군위읍 동부리 409-1번지', '대구광역시 군위군 동서5길 5-10 (군위읍 동부리)', 1, 0, '19921123', '19920629', 22.68, '단독주택', 2772025021), (27720250220221, '대구광역시 군위군 군위읍 서부리 22-1번지', None, 3, 0, '19901006', None, 189.72, '제1종근린생활시설', 2772025022), (277202502201960, '대구광역시 군위군 군위읍 서부리 196번지', '대구광역시 군위군 중앙3길 19-11 (군위읍 서부리)', 1, 0, '19871022', None, 95.18, '단독주택', 2772025022)]\npopulation: [('대구광역시 중구', '81,015', '41,163', 1.97, '38,868', '42,147', '89,685', '45,209', 1.98, '42,950', '46,735', 271100, 271100), ('대구광역시 중구 동인동', '7,891', '4,809', 1.64, '3,940', '3,951', '8,401', '5,092', 1.65, '4,182', '4,219', 2711051700, 2711051700), ('대구광역시 중구 삼덕동', '6,395', '4,093', 1.56, '3,050', '3,345', '6,678', '4,177', 1.6, '3,243', '3,435', 2711054500, 2711054500)]\ngas: [('대구광역시 남구 이천동 121-70', 202401, '대구광역시 남구 명덕로68길 지상  79 (이천동) ', 694234, 2720010100012170, 2720010100), ('대구광역시 남구 이천동 121-70', 202402, '대구광역시 남구 명덕로68길 지상  77 (이천동) ', 779517, 2720010100012170, 2720010100), ('대구광역시 남구 이천동 121-70', 202403, '대구광역시 남구 명덕로68길 지상  79 (이천동) ', 624218, 2720010100012170, 2720010100)]"

In [ ]:
schema_dict

{'tables': {'electricity': {'지번주소': ['TEXT',
    True,
    ['대구광역시 남구 이천동 121-70', '대구광역시 남구 이천동 121-70', '대구광역시 남구 이천동 121-70']],
   '사용년월': ['NUMBER', True, [202401, 202402, 202403]],
   '도로명주소': ['TEXT',
    True,
    ['대구광역시 남구 명덕로68길 지상  79 (이천동) ',
     '대구광역시 남구 명덕로68길 지상  77 (이천동) ',
     '대구광역시 남구 명덕로68길 지상  77 (이천동) ']],
   '전기사용량': ['NUMBER', True, [180038, 181483, 163726]],
   'pnu': ['NUMBER',
    True,
    [2720010100012170, 2720010100012170, 2720010100012170]]},
  'building': {'pnu': ['NUMBER',
    True,
    [277202502104091, 27720250220221, 277202502201960]],
   '지번주소': ['TEXT',
    True,
    ['대구광역시 군위군 군위읍 동부리 409-1번지',
     '대구광역시 군위군 군위읍 서부리 22-1번지',
     '대구광역시 군위군 군위읍 서부리 196번지']],
   '도로명주소': ['TEXT',
    True,
    ['대구광역시 군위군 동서5길 5-10 (군위읍 동부리)', None, '대구광역시 군위군 중앙3길 19-11 (군위읍 서부리)']],
   '지상층수': ['NUMBER', True, [1, 3, 1]],
   '지하층수': ['NUMBER', True, [0, 0, 0]],
   '사용승인일': ['TEXT', True, ['19921123', '19901006', '19871022']],
   '착공일': ['TEXT', True, ['19920629', None, None]],
   '면적': ['NUMBER', True, [22.68, 189.72, 95.18]],
   '용도': ['TEXT', True, ['단독주택', '제1종근린생활시설', '단독주택']],
   '법정동코드PNU': ['NUMBER', True, [2772025021, 2772025022, 2772025022]]},
  'population': {'지번주소': ['TEXT',
    True,
    ['대구광역시 중구', '대구광역시 중구 동인동', '대구광역시 중구 삼덕동']],
   '2023년_총인구수': ['TEXT', True, ['81,015', '7,891', '6,395']],
   '2023년_세대수': ['TEXT', True, ['41,163', '4,809', '4,093']],
   '2023년_세대당 인구': ['NUMBER', True, [1.97, 1.64, 1.56]],
   '2023년_남자 인구수': ['TEXT', True, ['38,868', '3,940', '3,050']],
   '2023년_여자 인구수': ['TEXT', True, ['42,147', '3,951', '3,345']],
   '2024년_총인구수': ['TEXT', True, ['89,685', '8,401', '6,678']],
   '2024년_세대수': ['TEXT', True, ['45,209', '5,092', '4,177']],
   '2024년_세대당 인구': ['NUMBER', True, [1.98, 1.65, 1.6]],
   '2024년_남자 인구수': ['TEXT', True, ['42,950', '4,182', '3,243']],
   '2024년_여자 인구수': ['TEXT', True, ['46,735', '4,219', '3,435']],
   'pnu': ['NUMBER', True, [271100, 2711051700, 2711054500]],
   '법정동코드PNU': ['NUMBER', True, [271100, 2711051700, 2711054500]]},
  'gas': {'지번주소': ['TEXT',
    True,
    ['대구광역시 남구 이천동 121-70', '대구광역시 남구 이천동 121-70', '대구광역시 남구 이천동 121-70']],
   '사용년월': ['NUMBER', True, [202401, 202402, 202403]],
   '도로명주소': ['TEXT',
    True,
    ['대구광역시 남구 명덕로68길 지상  79 (이천동) ',
     '대구광역시 남구 명덕로68길 지상  77 (이천동) ',
     '대구광역시 남구 명덕로68길 지상  79 (이천동) ']],
   '가스사용량': ['NUMBER', True, [694234, 779517, 624218]],
   'pnu': ['NUMBER',
    True,
    [2720010100012170, 2720010100012170, 2720010100012170]],
   '법정동코드PNU': ['NUMBER', True, [2720010100, 2720010100, 2720010100]]}},
 'foreign_keys': []}

In [ ]:
# prompt: /content/drive/MyDrive/questions.csv 아니 pandas로

file_path = '/content/drive/MyDrive/questions.csv'
questions = pd.read_csv(file_path)

print(questions[70:80])

                                                   문제
70  대구시에서 인구가 5,000명 이상인 동 중, 2023년 1인당 전기 사용량이 가장...
71   2023년 동별 연면적 총합 대비 도시가스 사용량 비율이 가장 높은 지역은 어디인가요?
72  건축 연도 기준으로 1990년 이전 건물만 필터링했을 때, 대구시 동별 평균 에너지...
73  대구시에서 건물 용도와 층수 조합별(예: 주거용+10층 이상)로 평균 전기 사용량을...
74  동별 전체 건물 중 상업용 비중이 50% 이상인 지역의 2023년 월별 전기 사용량...
75  대구시에서 에너지 사용량 상위 10%에 해당하는 건축물들의 평균 건축 연도는 언제인가요?
76     대구시 전체에서 건물 용도별 평균 전기 사용량의 분산이 가장 큰 용도는 무엇인가요?
77  2023년 에너지 사용량이 전년 대비 20% 이상 증가한 동의 수는 몇 곳이며, 해...
78  대구시 동별로 2023년 전기 사용량 피크(가장 높은 월)는 언제이며, 각 동의 피...
79  수성구에서 인구 대비 건축물 수가 많은 동의 에너지 소비 패턴이 다른 동들과 어떤 ...

In [ ]:
# prompt: /content/drive/MyDrive/output.csv 열어줘
import pandas as pd
output = pd.read_csv('/content/drive/MyDrive/output.csv')
# 또는 pd.read_csv('/content/drive/MyDrive/output.csv', encoding='cp949') 등 인코딩 지정 가능
output_list = output['SQL_Query']
output_list = output_list.tolist()

In [ ]:
import re
def extract_sql(text):
    try:
        return re.findall(r"```(?:\w*\n)?(.*?)```", text, re.DOTALL)[0].strip()
    except IndexError:
        return None  # 블록이 없을 경우 None 반환
# output_df
output['extracted_sql'] = output['SQL_Query'].apply(extract_sql)

In [ ]:
schema = {'building': 'Table: building\n  - pnu (TEXT)\n  - 지번주소 (TEXT)\n  - 도로명주소 (TEXT)\n  - 지상층수 (TEXT)\n  - 지하층수 (TEXT)\n  - 사용승인일 (TEXT)\n  - 착공일 (TEXT)\n  - 면적 (TEXT)\n  - 용도 (TEXT)',
'energy_usage': 'Table: energy_usage\n  - 지번주소 (TEXT)\n  - 사용년월 (BIGINT)\n  - 도로명주소 (TEXT)\n  - 전기사용량 (BIGINT)\n  - pnu (TEXT)',
'population': 'Table: population\n  - 지번주소 (TEXT)\n  - 2023년_총인구수 (TEXT)\n  - 2023년_세대수 (TEXT)\n  - 2023년_세대당 인구 (FLOAT)\n  - 2023년_남자 인구수 (TEXT)\n  - 2023년_여자 인구수 (TEXT)\n  - 2024년_총인구수 (TEXT)\n  - 2024년_세대수 (TEXT)\n  - 2024년_세대당 인구 (FLOAT)\n  - 2024년_남자 인구수 (TEXT)\n  - 2024년_여자 인구수 (TEXT)\n  - pnu (TEXT)'}

In [ ]:
import openai
import os

prompt = """schema:{schema}\nquestion:{question}\nsql 쿼리로 만들어줘"""
prompt_cw_temp_sft = """Given the following database schema and question, your task is to write a valid SQL query whose execution will accurately answer the question. If the value below the incomplete SQL query is not empty, your task is to complete it into a full SQL query. Remember to end the query with a semicolom ```;```.

Database schema:
{ds}

Sample rows of each table:
{sr}

Question:
{qs}

Answer the question by a SQL query only with no explanation:
"""
# input = prompt.format(schema=schema,question=question)
#openai
# prompt_cw_temp_sft.format(ds=database_schema, sr=examples, qs=question)
from openai import OpenAI

client = OpenAI()

In [ ]:
models = openai.models.list()
models
# for model in models['data']:
    # print(model)

SyncPage[Model](data=[Model(id='dall-e-2', created=1698798177, object='model', owned_by='system'), Model(id='gpt-4o-mini-2024-07-18', created=1721172717, object='model', owned_by='system'), Model(id='gpt-4o-mini', created=1721172741, object='model', owned_by='system'), Model(id='babbage-002', created=1692634615, object='model', owned_by='system'), Model(id='gpt-4o-2024-11-20', created=1739331543, object='model', owned_by='system'), Model(id='whisper-1', created=1677532384, object='model', owned_by='openai-internal'), Model(id='gpt-4o-mini-search-preview', created=1741391161, object='model', owned_by='system'), Model(id='gpt-4o-mini-search-preview-2025-03-11', created=1741390858, object='model', owned_by='system'), Model(id='davinci-002', created=1692634301, object='model', owned_by='system'), Model(id='tts-1-hd', created=1699046015, object='model', owned_by='system'), Model(id='gpt-4.1-2025-04-14', created=1744315746, object='model', owned_by='system'), Model(id='gpt-4-turbo', created=1712361441, object='model', owned_by='system'), Model(id='gpt-4-turbo-2024-04-09', created=1712601677, object='model', owned_by='system'), Model(id='o3-mini-2025-01-31', created=1738010200, object='model', owned_by='system'), Model(id='gpt-4.1', created=1744316542, object='model', owned_by='system'), Model(id='gpt-3.5-turbo-instruct-0914', created=1694122472, object='model', owned_by='system'), Model(id='gpt-4.1-mini-2025-04-14', created=1744317547, object='model', owned_by='system'), Model(id='gpt-4.1-mini', created=1744318173, object='model', owned_by='system'), Model(id='gpt-3.5-turbo-instruct', created=1692901427, object='model', owned_by='system'), Model(id='gpt-4o-mini-tts', created=1742403959, object='model', owned_by='system'), Model(id='gpt-4.1-nano-2025-04-14', created=1744321025, object='model', owned_by='system'), Model(id='gpt-4o', created=1715367049, object='model', owned_by='system'), Model(id='o4-mini-2025-04-16', created=1744133506, object='model', owned_by='system'), Model(id='gpt-4', created=1687882411, object='model', owned_by='openai'), Model(id='text-embedding-ada-002', created=1671217299, object='model', owned_by='openai-internal'), Model(id='o1-2024-12-17', created=1734326976, object='model', owned_by='system'), Model(id='dall-e-3', created=1698785189, object='model', owned_by='system'), Model(id='tts-1-hd-1106', created=1699053533, object='model', owned_by='system'), Model(id='o3-mini', created=1737146383, object='model', owned_by='system'), Model(id='gpt-4o-audio-preview', created=1727460443, object='model', owned_by='system'), Model(id='gpt-4o-2024-05-13', created=1715368132, object='model', owned_by='system'), Model(id='gpt-4o-search-preview-2025-03-11', created=1741388170, object='model', owned_by='system'), Model(id='gpt-4o-search-preview', created=1741388720, object='model', owned_by='system'), Model(id='gpt-3.5-turbo-16k', created=1683758102, object='model', owned_by='openai-internal'), Model(id='o1-mini', created=1725649008, object='model', owned_by='system'), Model(id='gpt-4-0613', created=1686588896, object='model', owned_by='openai'), Model(id='gpt-4o-realtime-preview', created=1727659998, object='model', owned_by='system'), Model(id='o1-mini-2024-09-12', created=1725648979, object='model', owned_by='system'), Model(id='gpt-4.1-nano', created=1744321707, object='model', owned_by='system'), Model(id='gpt-4o-transcribe', created=1742068463, object='model', owned_by='system'), Model(id='gpt-4o-2024-08-06', created=1722814719, object='model', owned_by='system'), Model(id='gpt-4.5-preview', created=1740623059, object='model', owned_by='system'), Model(id='gpt-4.5-preview-2025-02-27', created=1740623304, object='model', owned_by='system'), Model(id='gpt-4-turbo-preview', created=1706037777, object='model', owned_by='system'), Model(id='gpt-4-0125-preview', created=1706037612, object='model', owned_by='system'), Model(id='gpt-4o-realtime-preview-2024-10-01', created=1727131766, object='model', owned_by='system'), Model(id='gpt-4-1106-preview', created=1698957206, object='model', owned_by='system'), Model(id='gpt-3.5-turbo', created=1677610602, object='model', owned_by='openai'), Model(id='gpt-4o-mini-realtime-preview-2024-12-17', created=1734112601, object='model', owned_by='system'), Model(id='gpt-4o-mini-audio-preview-2024-12-17', created=1734115920, object='model', owned_by='system'), Model(id='chatgpt-4o-latest', created=1723515131, object='model', owned_by='system'), Model(id='gpt-4o-mini-realtime-preview', created=1734387380, object='model', owned_by='system'), Model(id='o4-mini', created=1744225351, object='model', owned_by='system'), Model(id='gpt-4o-audio-preview-2024-12-17', created=1734034239, object='model', owned_by='system'), Model(id='o1-pro-2025-03-19', created=1742251504, object='model', owned_by='system'), Model(id='gpt-3.5-turbo-1106', created=1698959748, object='model', owned_by='system'), Model(id='o1', created=1734375816, object='model', owned_by='system'), Model(id='tts-1-1106', created=1699053241, object='model', owned_by='system'), Model(id='gpt-4o-audio-preview-2024-10-01', created=1727389042, object='model', owned_by='system'), Model(id='tts-1', created=1681940951, object='model', owned_by='openai-internal'), Model(id='o1-pro', created=1742251791, object='model', owned_by='system'), Model(id='gpt-3.5-turbo-0125', created=1706048358, object='model', owned_by='system'), Model(id='codex-mini-latest', created=1746673257, object='model', owned_by='system'), Model(id='gpt-4o-realtime-preview-2024-12-17', created=1733945430, object='model', owned_by='system'), Model(id='gpt-4o-mini-audio-preview', created=1734387424, object='model', owned_by='system'), Model(id='text-embedding-3-small', created=1705948997, object='model', owned_by='system'), Model(id='text-embedding-3-large', created=1705953180, object='model', owned_by='system'), Model(id='gpt-4o-mini-transcribe', created=1742068596, object='model', owned_by='system'), Model(id='o1-preview', created=1725648897, object='model', owned_by='system'), Model(id='o1-preview-2024-09-12', created=1725648865, object='model', owned_by='system'), Model(id='omni-moderation-2024-09-26', created=1732734466, object='model', owned_by='system'), Model(id='omni-moderation-latest', created=1731689265, object='model', owned_by='system'), Model(id='gpt-image-1', created=1745517030, object='model', owned_by='system')], object='list')

In [ ]:

for i in range(10):
  print(output['문제'][i])
  print(output['extracted_sql'][i])
  prompt = output['문제'][i] + output['extracted_sql'][i] + 'is it right schema query without considering schema?'
  #openai chatcompletion with api key

from openai import OpenAI

client = OpenAI()
response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "system", "content": "You are a helpful SQLite assistant."},
        {"role": "user", "content": input}
    ]
)
print(i)
sql_query = response.choices[0].message.content
  print('--------------------')

대구시에서 연면적이 1만 제곱미터 이상인 건축물의 목록을 보여줘.
SELECT *
FROM building
WHERE CAST(면적 AS FLOAT) >= 10000;
--------------------
대구광역시 수성구에 위치한 업무시설 건축물 중 2023년 기준으로 사용 중인 건물은?
SELECT *
FROM building
WHERE 도로명주소 LIKE '%수성구%'
  AND 용도 LIKE '%업무%'
  AND 사용승인일 IS NOT NULL
--------------------
대구시 동구에 있는 건물 중 난방 방식이 지역난방인 건물만 찾아줘.
SELECT *
FROM building
WHERE 지번주소 LIKE '%동구%'
AND 용도 LIKE '%지역난방%';
--------------------
대구시 내 지하층이 2개 이상인 건축물을 알려줘.
SELECT *
FROM building
WHERE 지하층수 IS NOT NULL AND CAST(지하층수 AS INTEGER) >= 2;
--------------------
대구시 북구에서 2022년에 건축된 건물은 몇 개야?
SELECT COUNT(*) AS 건물_수
FROM building
WHERE 지번주소 LIKE '%북구%'
AND 착공일 BETWEEN '2022-01-01' AND '2022-12-31';
--------------------
대구 달성군에서 3층 이상인 교육시설 건축물을 찾아줘.
SELECT *
FROM building
WHERE 지상층수 >= '3'
  AND 용도 LIKE '%교육%'; -- '교육'이라는 키워드를 포함하는 용도
--------------------
2023년 기준으로 대구시 내에서 사용 승인일이 10년 이상 경과한 건축물만 보여줘.
SELECT *
FROM building
WHERE 사용승인일 <= strftime('%Y', 'now', '-10 years')
AND 지번주소 LIKE '%대구%'
--------------------
대구 중구에서 냉방용 전기 사용량이 존재하는 건물 목록을 출력해줘.
SELECT b.*
FROM building b
JOIN energy_usage e ON b.pnu = e.pnu
WHERE b.지번주소 LIKE '%대구 중구%'
AND e.전기사용량 > 0;
--------------------
대구시 수성구 범어동에 위치한 건축 연도가 2010년 이후인 건물의 ID를 알려줘.
SELECT pnu
FROM building
WHERE 지번주소 LIKE '%범어동%'
  AND 사용승인일 >= '2010-01-01';
--------------------
대구시에서 5층 이상이고, 주용도가 ‘업무시설’인 건축물만 보여줘
SELECT *
FROM building
WHERE 지상층수 >= '5' AND 용도 = '업무시설' AND 지번주소 LIKE '대구%'
--------------------

In [ ]:
import sqlite3
import re
success_count = 0
#체크
for i in range(77,100):
  sql_query = re.findall(r"```(?:\w*\n)?(.*?)```", output_list[i], re.DOTALL)[0]
  # print(sql_query)

  conn = sqlite3.connect("your_database.db")


  try:
      with engine.connect() as conn:
          result = conn.execute(text(sql_query))
          rows = result.fetchall()
          print(f"✅ Success:{i}question")
          # print(f'{rows[0]}')
          success_count += 1
  except Exception as e:
          print(f"❌ Error:\n {i}question")

  print(f"\n총 성공한 쿼리 수: {success_count}")

❌ Error:
 28question
✅ Success:29question
✅ Success:30question
✅ Success:31question
✅ Success:32question
✅ Success:33question
✅ Success:34question
✅ Success:35question
✅ Success:36question
✅ Success:37question
✅ Success:38question
❌ Error:
 39question
✅ Success:40question
❌ Error:
 41question
❌ Error:
 42question
✅ Success:43question
❌ Error:
 44question
✅ Success:45question
✅ Success:46question
❌ Error:
 47question
✅ Success:48question
✅ Success:49question
❌ Error:
 50question
❌ Error:
 51question
✅ Success:52question
✅ Success:53question
❌ Error:
 54question
✅ Success:55question
❌ Error:
 56question
✅ Success:57question
✅ Success:58question
✅ Success:59question
❌ Error:
 60question
❌ Error:
 61question
✅ Success:62question
✅ Success:63question
❌ Error:
 64question
✅ Success:65question
✅ Success:66question
✅ Success:67question
✅ Success:68question
❌ Error:
 69question
❌ Error:
 70question
✅ Success:71question
✅ Success:72question
✅ Success:73question
✅ Success:74question
❌ Error:
 75question
✅ Success:76question

In [ ]:
# ✅ Success:0question
# ✅ Success:1question
# ✅ Success:2question
# ✅ Success:3question
# ✅ Success:4question
# ✅ Success:5question
# ✅ Success:6question
# ✅ Success:7question
# ✅ Success:8question
# ✅ Success:9question
# ✅ Success:10question
# ❌ Error:
#  11question
# ✅ Success:12question
# ✅ Success:13question
# ❌ Error:
#  14question
# ✅ Success:15question
# ✅ Success:16question
# ❌ Error:
#  17question
# ❌ Error:
#  18question
# ✅ Success:19question
# ❌ Error:
#  20question
# ❌ Error:
#  21question
# ❌ Error:
#  22question
# ✅ Success:23question
# ✅ Success:24question
# ❌ Error:
#  25question
# ❌ Error:
#  26question
# ✅ Success:27question
❌ Error:
 28question
✅ Success:29question
✅ Success:30question
✅ Success:31question
✅ Success:32question
✅ Success:33question
✅ Success:34question
✅ Success:35question
✅ Success:36question
✅ Success:37question
✅ Success:38question
❌ Error:
 39question
✅ Success:40question
❌ Error:
 41question
❌ Error:
 42question
✅ Success:43question
❌ Error:
 44question
✅ Success:45question
✅ Success:46question
❌ Error:
 47question
✅ Success:48question
✅ Success:49question
❌ Error:
 50question
❌ Error:
 51question
✅ Success:52question
✅ Success:53question
❌ Error:
 54question
✅ Success:55question
❌ Error:
 56question
✅ Success:57question
✅ Success:58question
✅ Success:59question
❌ Error:
 60question
❌ Error:
 61question
✅ Success:62question
✅ Success:63question
❌ Error:
 64question
✅ Success:65question
✅ Success:66question
✅ Success:67question
✅ Success:68question
❌ Error:
 69question
❌ Error:
 70question
✅ Success:71question
✅ Success:72question
✅ Success:73question
✅ Success:74question
❌ Error:
 75question
✅ Success:76question
print(output_list[27])

```sql
SELECT DISTINCT p.지번주소
FROM population p
JOIN gas g ON p.pnu = g.pnu
WHERE p.2023년_총인구수 >= '10000'
AND g.가스사용량 >= (SELECT AVG(가스사용량) FROM gas WHERE 지번주소 LIKE '대구광역시 북구%')
AND p.지번주소 LIKE '대구광역시 북구%'
;

In [ ]:
print(output_list[77])

NameError: name 'output_list' is not defined

In [ ]:
print(output['문제'][30:41])
# print(output['extracted_sql'][41])

print(output['SQL_Query'][30:41])

30           대구시 동별로 2023년 전기 사용량이 가장 많은 건물 10곳은 어디인가요?
31        2023년에 중구 삼덕동에서 도시가스를 가장 많이 사용한 건물 유형은 무엇인가요?
32       대구시에서 2023년 동안 냉방용 전기 사용량이 급증한 상업용 건물은 몇 동입니까?
33    건축 연도가 2000년 이전인 건물들 중, 2023년 전기 사용량이 평균 이상인 건...
34        2023년 수성구 범어동에서 지역난방 사용량이 가장 높은 건물은 어떤 용도인가요?
35    남구 대명동에서 2022년 대비 2023년 전기 사용량이 20% 이상 증가한 건물 ...
36    2023년 기준 대구시에서 용도별 평균 도시가스 사용량이 가장 높은 순으로 정렬해주세요.
37    대구시 건축물 중에서 지상층수가 10층 이상이고 전기 사용량이 2023년 기준 상위...
38    달서구에서 에너지 사용량 총합이 가장 높은 건축물대장 ID(bdrg_lnkg_id)...
39    대구시 동별로 전기, 도시가스, 지역난방 중 어떤 에너지원을 가장 많이 사용하는지 ...
40              2023년 기준 인구당 평균 전기 사용량이 가장 높은 동은 어디인가요?
Name: 문제, dtype: object
30    대구시 동별로 2023년 전기 사용량이 가장 많은 건물 10곳을 찾기 위한 SQL ...
31    주어진 스키마에 따르면, 도시가스 사용량에 대한 테이블은 없지만, 에너지 사용량 데...
32    상업용 건물의 냉방용 전기 사용량이 급증한 경우를 판단하기 위해, 특정 기간 동안의...
33    건축 연도가 2000년 이전인 건물들을 찾고, 이들 중에서 2023년 전기 사용량이...
34    지역난방 사용량에 대한 구체적인 데이터는 주어진 스키마에는 없지만, 일반적으로 에너...
35    아래의 SQL 쿼리는 남구 대명동에서 2022년 대비 2023년 전기 사용량이 20...
36    대구시에서 용도별로 2023년 기준 평균 도시가스 사용량을 구하는 SQL 쿼리는 아...
37    대구시 건축물 중에서 지상층수가 10층 이상이고 전기 사용량이 2023년 기준 상위...
38    달서구에서 에너지 사용량 총합이 가장 높은 건축물대장 ID(pnu)를 찾기 위해서는...
39    전기, 도시가스, 지역난방의 사용량을 비교하기 위해서는 각각의 에너지 사용량 테이블...
40    2023년 기준 인구당 평균 전기 사용량이 가장 높은 동을 찾기 위해, `popul...
Name: SQL_Query, dtype: object

In [ ]:
# for i in range(100):
#   print(f'{i}번째 문제')
#   print(output['문제'][i])
#   print(output['extracted_sql'][i])
#   print('-------------------------------------')

In [ ]:
output

,문제,SQL_Query,extracted_sql
0,대구시에서 연면적이 1만 제곱미터 이상인 건축물의 목록을 보여줘.,대구시에서 연면적이 1만 제곱미터 이상인 건축물의 목록을 조회하는 SQL 쿼리를 아...,SELECT *\nFROM building\nWHERE CAST(면적 AS FLOA...
1,대구광역시 수성구에 위치한 업무시설 건축물 중 2023년 기준으로 사용 중인 건물은?,대구광역시 수성구에 위치한 업무시설 건축물 중 2023년 기준으로 사용 중인 건물을...,SELECT *\nFROM building\nWHERE 도로명주소 LIKE '%수성...
2,대구시 동구에 있는 건물 중 난방 방식이 지역난방인 건물만 찾아줘.,대구시 동구에 있는 건물 중 난방 방식이 지역난방인 경우에 대한 SQL 쿼리를 작성...,SELECT *\nFROM building\nWHERE 지번주소 LIKE '%동구%...
3,대구시 내 지하층이 2개 이상인 건축물을 알려줘.,아래는 대구시 내 지하층이 2개 이상인 건축물을 찾기 위한 SQL 쿼리입니다.\n\...,SELECT * \nFROM building \nWHERE 지하층수 IS NOT N...
4,대구시 북구에서 2022년에 건축된 건물은 몇 개야?,대구시 북구에서 2022년에 건축된 건물을 찾기 위한 SQL 쿼리는 다음과 같습니다...,SELECT COUNT(*) AS 건물_수\nFROM building\nWHERE ...
...,...,...,...
95,대구시 동별로 건축물 수 대비 인구 수 비율이 높은 지역과 에너지 사용량 간의 관계...,"대구시 동별로 건축물 수 대비 인구 수 비율을 계산하고, 해당 비율이 높은 지역들의...","WITH population_data AS (\n SELECT 지번주소,\n ..."
96,2023년 한 해 동안 에너지 사용량 변동이 가장 일정한(표준편차 가장 낮은) 동은...,에너지 사용량 변동이 가장 일정한 동(표준편차가 가장 낮은)은 `energy_usa...,WITH EnergyStats AS (\n SELECT \n 지번...
97,"2023년 대구시에서 전기, 도시가스, 지역난방 3종 모두 사용하는 건물의 평균 에...","위의 스키마에 기반하여 대구시에서 전기, 도시가스, 지역난방 3종 모두 사용하는 건...",SELECT AVG(e.전기사용량) AS 평균_전기사용량\nFROM energy_u...
98,대구시 동별 건축물 용도 다변성과 에너지 사용량 분산의 관계를 통계적으로 분석해주세요.,대구시 동별 건축물 용도 다변성과 에너지 사용량 분산의 관계를 통계적으로 분석하기 ...,WITH BuildingUsage AS (\n SELECT\n S...
99,"건물 수, 총 연면적, 에너지 사용량, 인구를 기준으로 동별 종합 에너지 효율 등급...",동별 종합 에너지 효율 등급을 산정하기 위해 필요한 정보를 포함한 SQL 쿼리를 작...,WITH building_data AS (\n SELECT \n ...

✅ Success:0question

총 성공한 쿼리 수: 1
✅ Success:1question

총 성공한 쿼리 수: 2
❌ Error:
 2question

총 성공한 쿼리 수: 2
✅ Success:3question

총 성공한 쿼리 수: 3
✅ Success:4question

총 성공한 쿼리 수: 4
✅ Success:5question

총 성공한 쿼리 수: 5
✅ Success:6question

총 성공한 쿼리 수: 6
✅ Success:7question

총 성공한 쿼리 수: 7
✅ Success:8question

총 성공한 쿼리 수: 8
✅ Success:9question

총 성공한 쿼리 수: 9
✅ Success:10question

총 성공한 쿼리 수: 10
❌ Error:
 11question

✅ Success:13question

총 성공한 쿼리 수: 1
❌ Error:
 14question

총 성공한 쿼리 수: 1
✅ Success:15question

총 성공한 쿼리 수: 2
✅ Success:16question

총 성공한 쿼리 수: 3
❌ Error:
 17question

총 성공한 쿼리 수: 3
❌ Error:
 18question

총 성공한 쿼리 수: 3
✅ Success:19question

총 성공한 쿼리 수: 4
✅ Success:20question

총 성공한 쿼리 수: 5
❌ Error:
 21question

총 성공한 쿼리 수: 5
❌ Error:
 22question

총 성공한 쿼리 수: 5
✅ Success:23question

총 성공한 쿼리 수: 6
❌ Error:
 24question

총 성공한 쿼리 수: 6
❌ Error:
 25question

총 성공한 쿼리 수: 6
❌ Error:
 26question

총 성공한 쿼리 수: 6
❌ Error:
 27question

총 성공한 쿼리 수: 6
❌ Error:
 28question

총 성공한 쿼리 수: 6
✅ Success:29question

총 성공한 쿼리 수: 7

In [ ]:
output.to_csv('output_re.csv', index=False)

✅ Success:0question

총 성공한 쿼리 수: 1
✅ Success:1question

총 성공한 쿼리 수: 2
✅ Success:2question

총 성공한 쿼리 수: 3
✅ Success:3question

총 성공한 쿼리 수: 4
✅ Success:4question

총 성공한 쿼리 수: 5
✅ Success:5question

총 성공한 쿼리 수: 6
✅ Success:6question

총 성공한 쿼리 수: 7
✅ Success:7question

총 성공한 쿼리 수: 8
✅ Success:8question

총 성공한 쿼리 수: 9
✅ Success:9question

총 성공한 쿼리 수: 10
✅ Success:10question

총 성공한 쿼리 수: 11
❌ Error:
 11question

총 성공한 쿼리 수: 11
✅ Success:12question

총 성공한 쿼리 수: 12
✅ Success:13question

총 성공한 쿼리 수: 13
✅ Success:14question

총 성공한 쿼리 수: 14
✅ Success:15question

총 성공한 쿼리 수: 15
❌ Error:
 16question

총 성공한 쿼리 수: 15
✅ Success:17question

총 성공한 쿼리 수: 16
❌ Error:
 18question

총 성공한 쿼리 수: 16
✅ Success:19question

총 성공한 쿼리 수: 17
✅ Success:20question


총 성공한 쿼리 수: 17
❌ Error:
 21question

총 성공한 쿼리 수: 17
❌ Error:
 22question

총 성공한 쿼리 수: 18
✅ Success:23question

총 성공한 쿼리 수: 18
❌ Error:
 24question

총 성공한 쿼리 수: 18
❌ Error:
 25question

총 성공한 쿼리 수: 18
❌ Error:
 26question

총 성공한 쿼리 수: 18
❌ Error:
 27question

총 성공한 쿼리 수: 18
❌ Error:
 28question

총 성공한 쿼리 수: 18
❌ Error:
 29question

총 성공한 쿼리 수: 19
✅ Success:30question

총 성공한 쿼리 수: 1
✅ Success:31question

총 성공한 쿼리 수: 2
❌ Error:
 32question

총 성공한 쿼리 수: 1
✅ Success:33question

✅ Success:34question

총 성공한 쿼리 수: 1
✅ Success:35question

총 성공한 쿼리 수: 2
✅ Success:36question

총 성공한 쿼리 수: 3
✅ Success:37question

총 성공한 쿼리 수: 4
✅ Success:38question

총 성공한 쿼리 수: 5
❌ Error:
 39question

총 성공한 쿼리 수: 5
❌ Error:
 40question

총 성공한 쿼리 수: 5
❌ Error:
 41question

총 성공한 쿼리 수: 5
❌ Error:
 42question

총 성공한 쿼리 수: 5
❌ Error:
 43question

총 성공한 쿼리 수: 5
❌ Error:
 44question

총 성공한 쿼리 수: 5
❌ Error:
 45question

총 성공한 쿼리 수: 5
❌ Error:
 46question

총 성공한 쿼리 수: 5
❌ Error:
 47question

총 성공한 쿼리 수: 5
❌ Error:
 48question

총 성공한 쿼리 수: 5
❌ Error:
 49question

총 성공한 쿼리 수: 5

✅ Success:50question

총 성공한 쿼리 수: 1
❌ Error:
 51question

총 성공한 쿼리 수: 1
❌ Error:
 52question

총 성공한 쿼리 수: 1
✅ Success:53question

총 성공한 쿼리 수: 2
✅ Success:54question

총 성공한 쿼리 수: 3
❌ Error:
 55question

총 성공한 쿼리 수: 3
❌ Error:
 56question

총 성공한 쿼리 수: 3
✅ Success:57question

총 성공한 쿼리 수: 4
❌ Error:
 58question

총 성공한 쿼리 수: 4
❌ Error:
 59question

총 성공한 쿼리 수: 4
❌ Error:
 60question

총 성공한 쿼리 수: 4
✅ Success:61question

총 성공한 쿼리 수: 5
✅ Success:62question

총 성공한 쿼리 수: 6
✅ Success:63question

총 성공한 쿼리 수: 7
❌ Error:
 64question

총 성공한 쿼리 수: 7
❌ Error:
 65question

총 성공한 쿼리 수: 7
❌ Error:
 66question

총 성공한 쿼리 수: 7
❌ Error:
 67question

총 성공한 쿼리 수: 7
❌ Error:
 68question

총 성공한 쿼리 수: 7
❌ Error:
 69question

총 성공한 쿼리 수: 7
❌ Error:
 70question

총 성공한 쿼리 수: 7
✅ Success:71question

총 성공한 쿼리 수: 8
❌ Error:
 72question

✅ Success:73question

총 성공한 쿼리 수: 1
✅ Success:74question

총 성공한 쿼리 수: 2
❌ Error:
 75question

총 성공한 쿼리 수: 2
❌ Error:
 76question

총 성공한 쿼리 수: 2
❌ Error:
 77question

총 성공한 쿼리 수: 2
❌ Error:
 78question

총 성공한 쿼리 수: 2
❌ Error:
 79question

총 성공한 쿼리 수: 2
❌ Error:
 80question

총 성공한 쿼리 수: 2
✅ Success:81question

총 성공한 쿼리 수: 3
❌ Error:
 82question

총 성공한 쿼리 수: 3
✅ Success:83question

총 성공한 쿼리 수: 4
❌ Error:
 84question

총 성공한 쿼리 수: 4
❌ Error:
 85question

총 성공한 쿼리 수: 4
❌ Error:
 86question

총 성공한 쿼리 수: 4
✅ Success:87question

총 성공한 쿼리 수: 5
✅ Success:88question

총 성공한 쿼리 수: 6
❌ Error:
 89question

총 성공한 쿼리 수: 6
❌ Error:
 90question

총 성공한 쿼리 수: 6
❌ Error:
 91question

총 성공한 쿼리 수: 6
✅ Success:92question

총 성공한 쿼리 수: 7
❌ Error:
 93question

총 성공한 쿼리 수: 7
❌ Error:
 94question

총 성공한 쿼리 수: 7
❌ Error:
 95question

총 성공한 쿼리 수: 7
❌ Error:
 96question

총 성공한 쿼리 수: 7
❌ Error:
 97question

총 성공한 쿼리 수: 7
❌ Error:
 98question

총 성공한 쿼리 수: 7
❌ Error:
 99question

In [ ]:
# prompt: /content/drive/MyDrive/elec2324.csv

elec2324 = pd.read_csv('/content/drive/MyDrive/elec2324.csv')

In [ ]:
def get_schema_info(db_path):
    # engine = create_engine(f'sqlite:///{db_path}')

    inspector = inspect(engine)
    schema_info = {}

    tables = inspector.get_table_names()
    for table_name in tables:
        columns = inspector.get_columns(table_name)

        table_info = f"Table: {table_name}\n"
        table_info += "\n".join(f"  - {col['name']} ({col['type']})" for col in columns)
        schema_info[table_name] = table_info

    return schema_info

schema = get_schema_info("/content/database.db")

In [ ]:
schema
# {'building': 'Table: building\n  - pnu (TEXT)\n  - 지번주소 (TEXT)\n  - 도로명주소 (TEXT)\n  - 지상층수 (TEXT)\n  - 지하층수 (TEXT)\n  - 사용승인일 (TEXT)\n  - 착공일 (TEXT)\n  - 면적 (TEXT)\n  - 용도 (TEXT)',
#  'energy_usage': 'Table: energy_usage\n  - 지번주소 (TEXT)\n  - 사용년월 (BIGINT)\n  - 도로명주소 (TEXT)\n  - 전기사용량 (BIGINT)\n  - pnu (TEXT)',
#  'population': 'Table: population\n  - 지번주소 (TEXT)\n  - 2023년_총인구수 (TEXT)\n  - 2023년_세대수 (TEXT)\n  - 2023년_세대당 인구 (FLOAT)\n  - 2023년_남자 인구수 (TEXT)\n  - 2023년_여자 인구수 (TEXT)\n  - 2024년_총인구수 (TEXT)\n  - 2024년_세대수 (TEXT)\n  - 2024년_세대당 인구 (FLOAT)\n  - 2024년_남자 인구수 (TEXT)\n  - 2024년_여자 인구수 (TEXT)\n  - pnu (TEXT)'}

{'building': 'Table: building\n  - pnu (BIGINT)\n  - 지번주소 (TEXT)\n  - 도로명주소 (TEXT)\n  - 지상층수 (BIGINT)\n  - 지하층수 (BIGINT)\n  - 사용승인일 (TEXT)\n  - 착공일 (TEXT)\n  - 면적 (FLOAT)\n  - 용도 (TEXT)',
 'energy_usage': 'Table: energy_usage\n  - 지번주소 (TEXT)\n  - 사용년월 (BIGINT)\n  - 도로명주소 (TEXT)\n  - 전기사용량 (BIGINT)\n  - pnu (BIGINT)'}

In [ ]:
# po = po.iloc[:, 217:]
# prompt: /content/population.csv

po = pd.read_csv('/content/population.csv')

po = po.iloc[:, [0] + list(range(217, po.shape[1]))]
po["pnu"] = po.iloc[:, 145:].astype(str).replace("\.", "", regex=True).agg("".join, axis=1)
po["pnu"] = po["pnu"].str[:10]
po['행정구역']
po['행정구역'] = po['행정구역'].str.replace(r"\s*\(\d+\)", "", regex=True)
po = po.rename(columns={"행정구역": "지번주소"})
po
po.drop(columns=["시군구코드", "법정동코드"], inplace=True)

In [ ]:
po['행정구역']
po['행정구역'] = po['행정구역'].str.replace(r"\s*\(\d+\)", "", regex=True)
po = po.rename(columns={"행정구역": "지번주소"})
po
po.drop(columns=["시군구코드", "법정동코드"], inplace=True)

In [ ]:
import pandas as pd
po.rename(columns={"2023년01월_총인구수": "2023년_총인구수"}, inplace=True)
po.rename(columns={"2023년01월_세대수": "2023년_세대수"}, inplace=True)
po.rename(columns={"2023년01월_세대당 인구": "2023년_세대당 인구"}, inplace=True)
po.rename(columns={"2023년01월_남자 인구수": "2023년_남자 인구수"}, inplace=True)
po.rename(columns={"2023년01월_여자 인구수": "2023년_여자 인구수"}, inplace=True)
po.rename(columns={"2024년01월_총인구수": "2024년_총인구수"}, inplace=True)
po.rename(columns={"2024년01월_세대수": "2024년_세대수"}, inplace=True)
po.rename(columns={"2024년01월_세대당 인구": "2024년_세대당 인구"}, inplace=True)
po.rename(columns={"2024년01월_남자 인구수": "2024년_남자 인구수"}, inplace=True)
po.rename(columns={"2024년01월_여자 인구수": "2024년_여자 인구수"}, inplace=True)
# po.drop(columns=["2023년01월_남여 비율", "2024년01월_남여 비율"], inplace=True)
po.drop(columns=["2023년01월_남여 비율","2023년12월_남여 비율"], inplace=True)
po

In [ ]:
# simple_prompt = """schema:{schema}\n question:{question} sql 쿼리를 만들어줘 """

In [ ]:

prompt_cw_temp_sft = """Given the following database schema and question, your task is to write a valid SQL query whose execution will accurately answer the question. If the value below the incomplete SQL query is not empty, your task is to complete it into a full SQL query. Remember to end the query with a semicolom ```;```.

Database schema:
{ds}

Sample rows of each table:
{sr}

Question:
{qs}{hint}

Question hint:
{sql}

The incomplete SQL query:
{sql}

Answer the question by a SQL query only with no explanation:
"""#openai chatcompletion with api key
import openai
import os

prompt = """schema:{schema}\nquestion:{question}\nsql 쿼리로 만들어줘"""
# input = prompt.format(schema=schema,question=question)
#openai
from openai import OpenAI

client = OpenAI()

In [ ]:
schema = """{'building': 'Table: building\n  - pnu (BIGINT)\n  - 지번주소 (TEXT)\n  - 도로명주소 (TEXT)\n  - 지상층수 (BIGINT)\n  - 지하층수 (BIGINT)\n  - 사용승인일 (TEXT)\n  - 착공일 (TEXT)\n  - 면적 (FLOAT)\n  - 용도 (TEXT)',
 'energy_usage': 'Table: energy_usage\n  - 지번주소 (TEXT)\n  - 사용년월 (BIGINT)\n  - 도로명주소 (TEXT)\n  - 전기사용량 (BIGINT)\n  - pnu (BIGINT)'}"""

In [ ]:
file_path = '/content/drive/MyDrive/questions.csv'
questions = pd.read_csv(file_path)

In [ ]:
output_list = []
# prompt_cw_temp_sft.format(ds=database_schema, sr=examples, qs=question)

for i in range(100):
  q = questions['문제'][i]
  print(q)
  # input = prompt.format(schema=schema,question=q)
  input = prompt_cw_temp_sft.format(ds=database_schema, sr=examples, qs=q)

  response = client.chat.completions.create(
      model="gpt-4o-mini",
      messages=[
          {"role": "system", "content": "You are a helpful SQLite assistant."},
          {"role": "user", "content": input}
      ]
  )
  print(i)
  sql_query = response.choices[0].message.content
  # sql_query = response['choices'][0]['message']['content']
  output_list.append(sql_query)

대구시에서 연면적이 1만 제곱미터 이상인 건축물의 목록을 보여줘.
0
대구광역시 수성구에 위치한 업무시설 건축물 중 2023년 기준으로 사용 중인 건물은?
1
대구시 동구에 있는 건물 중 난방 방식이 지역난방인 건물만 찾아줘.
2
대구시 내 지하층이 2개 이상인 건축물을 알려줘.
3
대구시 북구에서 2022년에 건축된 건물은 몇 개야?
4
대구 달성군에서 3층 이상인 교육시설 건축물을 찾아줘.
5
2023년 기준으로 대구시 내에서 사용 승인일이 10년 이상 경과한 건축물만 보여줘.
6
대구 중구에서 냉방용 전기 사용량이 존재하는 건물 목록을 출력해줘.
7
대구시 수성구 범어동에 위치한 건축 연도가 2010년 이후인 건물의 ID를 알려줘.
8
대구시에서 5층 이상이고, 주용도가 ‘업무시설’인 건축물만 보여줘
9
대구시 전체에서 용도별(업무시설, 공동주택 등) 건물 수를 집계해줘
10
대구광역시 내 자치구별 평균 연면적을 비교해줘.
11
대구시 건물 중 2023년 도시가스 사용량 상위 10개 건물을 보여줘
12
대구 중구의 2022년 평균 전기 사용량은 얼마야?
13
대구시 각 구별 전력 사용량 합계를 구해서 높은 순으로 정렬해줘.
14
대구시 동별로 2023년 전기 사용량 평균과 최대값을 함께 보여줘.
15
대구시 전체에서 2023년 기준 에너지원별(전기, 도시가스, 지역난방) 총 사용량을 비교해줘.
16
대구시 각 동별 공동주택 수를 세고, 가장 많은 동을 알려줘
17
대구시에서 용도별 평균 에너지 사용량과 표준편차를 구해줘.
18
대구시 전체 건축물 중 층수에 따라 건물 수를 집계해서 바 차트로 나타내줘.
19
대구시 내 인구 5만 명 이상인 행정동에서 연면적 3천㎡ 이상 건물이 가장 많은 동은 어디야?
20
대구 동구 중 전기 사용량 대비 인구 수가 많은 지역은 어디야?
21
대구 남구에서 1인당 전기 사용량이 가장 높은 행정동은?
22
대구시에서 인구 밀도가 높은 지역에 있는 업무시설의 평균 에너지 소비량은?
23
대구 달서구에서 지역난방을 사용하는 공동주택의 평균 세대당 사용량은?
24
2023년 기준, 대구 동구에서 연면적 2천㎡ 이상 건물이 많고 인구는 적은 동은 어디야?
25
대구시에서 1인당 전기 사용량이 높은 동과 해당 동의 평균 건축 연면적의 관계를 분석해줘.
26
대구 북구에서 인구가 1만 명 이상이고, 도시가스 사용량이 평균 이상인 동은 어디야?
27
대구 달서구의 건물 중 지하층이 없는 건물만 필터링해서, 해당 지역의 1인당 에너지 소비량을 분석해줘.
28
대구 중구에서 인구 밀도는 높은데, 에너지 사용량이 낮은 동을 알려줘.
29
대구시 동별로 2023년 전기 사용량이 가장 많은 건물 10곳은 어디인가요?
30
2023년에 중구 삼덕동에서 도시가스를 가장 많이 사용한 건물 유형은 무엇인가요?
31
대구시에서 2023년 동안 냉방용 전기 사용량이 급증한 상업용 건물은 몇 동입니까?
32
건축 연도가 2000년 이전인 건물들 중, 2023년 전기 사용량이 평균 이상인 건물은 어디인가요?
33
2023년 수성구 범어동에서 지역난방 사용량이 가장 높은 건물은 어떤 용도인가요?
34
남구 대명동에서 2022년 대비 2023년 전기 사용량이 20% 이상 증가한 건물 수는 몇 개인가요?
35
2023년 기준 대구시에서 용도별 평균 도시가스 사용량이 가장 높은 순으로 정렬해주세요.
36
대구시 건축물 중에서 지상층수가 10층 이상이고 전기 사용량이 2023년 기준 상위 5%인 건물을 알려주세요.
37
달서구에서 에너지 사용량 총합이 가장 높은 건축물대장 ID(bdrg_lnkg_id)는 무엇인가요?
38
대구시 동별로 전기, 도시가스, 지역난방 중 어떤 에너지원을 가장 많이 사용하는지 알려주세요.
39
2023년 기준 인구당 평균 전기 사용량이 가장 높은 동은 어디인가요?
40
수성구에서 1인당 도시가스 사용량이 가장 많은 동은 어디입니까?
41
중구에서 노인 인구 비율이 높은 동의 에너지 사용량 평균은 어떻게 되나요?
42
대구시 동별로 인구 수와 에너지 사용량 간 상관관계를 분석해주세요.
43
2023년 중구 동별로 인구당 전기 사용량을 히트맵으로 보여주세요.
44
건물 연면적 대비 인구당 에너지 소비량이 가장 높은 동은 어디인가요?
45
대구시에서 외국인 인구 비율이 높은 동의 에너지 사용 패턴은 다른 동과 어떤 차이가 있나요?
46
달서구에서 청년 인구가 많은 동의 도시가스 사용량 평균은 어떻게 되나요?
47
수성구와 북구의 인구 구성에 따른 에너지 사용 특성 차이를 비교해주세요.
48
2023년 기준으로 인구 1인당 지역난방 사용량의 분포를 시각화해주세요.
49
2020년부터 2023년까지 연도별 에너지 사용량 증가율이 가장 큰 동은 어디인가요?
50
대구시 동별로 지난 3년간 전기 사용량의 증감 추세를 그래프로 보여주세요.
51
2023년 월별 도시가스 사용량 패턴이 뚜렷한 계절성을 보이는 동은 어디인가요?
52
2022년과 2023년을 비교했을 때, 동별로 지역난방 사용량이 감소한 지역은 어디인가요?
53
대구시의 상업시설에서 2023년 여름철 전기 사용량 피크가 발생한 시점은 언제인가요?
54
동별 월평균 전기 사용량을 2023년 기준으로 시계열 그래프로 보여주세요.
55
대구시의 연도별 전체 에너지 사용량 추이를 선 그래프로 시각화해주세요.
56
2023년 전기 사용량이 1월과 8월에 모두 높은 건물의 특성을 분석해주세요.
57
대구시에서 동별로 에너지 사용량의 변동성이 가장 큰 곳은 어디인가요?
58
전기·도시가스·지역난방 사용량의 월별 평균을 비교하는 막대그래프를 그려주세요.
59
대구시 동 중에서 건축물 수가 100개 이상이고, 인구당 도시가스 사용량이 평균 이상인 동을 알려주세요.
60
건축물 중 연면적이 5,000㎡ 이상이면서 2023년 에너지 사용량이 전체 평균 이상인 건물을 보여주세요.
61
수성구의 고층 건물(15층 이상) 중 2023년 전기 사용량이 낮은 순서로 상위 10개를 보여주세요.
62
대구시 전체에서 에너지 효율(사용량 대비 면적)이 가장 높은 건물 유형은 무엇인가요?
63
2023년 전기 사용량이 급증한 지역과 인구 증가가 함께 발생한 동을 찾아주세요.
64
2023년 동별 평균 전기 사용량과 평균 건축연도를 비교하여 상관관계를 분석해주세요.
65
2023년 기준, 대구시 내에서 건물당 평균 전기 사용량과 인구당 평균 사용량을 비교 분석해주세요.
66
달서구와 달성군의 주거용 건물에서 전기와 도시가스 사용량의 비중을 비교해주세요.
67
대구시 전체를 대상으로 용도별, 구별 에너지 사용량 분포를 다층 원형 차트로 보여주세요.
68
2023년 전기 사용량 상위 10개 동과 인구 밀도 상위 10개 동의 교집합을 보여주세요.
69
대구시에서 인구가 5,000명 이상인 동 중, 2023년 1인당 전기 사용량이 가장 높은 5개 동은 어디인가요?
70
2023년 동별 연면적 총합 대비 도시가스 사용량 비율이 가장 높은 지역은 어디인가요?
71
건축 연도 기준으로 1990년 이전 건물만 필터링했을 때, 대구시 동별 평균 에너지 사용량 분포를 알려주세요.
72
대구시에서 건물 용도와 층수 조합별(예: 주거용+10층 이상)로 평균 전기 사용량을 테이블로 보여주세요.
73
동별 전체 건물 중 상업용 비중이 50% 이상인 지역의 2023년 월별 전기 사용량 추이를 시각화해주세요.
74
대구시에서 에너지 사용량 상위 10%에 해당하는 건축물들의 평균 건축 연도는 언제인가요?
75
대구시 전체에서 건물 용도별 평균 전기 사용량의 분산이 가장 큰 용도는 무엇인가요?
76
2023년 에너지 사용량이 전년 대비 20% 이상 증가한 동의 수는 몇 곳이며, 해당 동들을 리스트업해주세요.
77
대구시 동별로 2023년 전기 사용량 피크(가장 높은 월)는 언제이며, 각 동의 피크값을 함께 보여주세요.
78
수성구에서 인구 대비 건축물 수가 많은 동의 에너지 소비 패턴이 다른 동들과 어떤 차이를 보이나요?
79
2023년 기준, 대구시의 동별 평균 전기 사용량과 평균 도시가스 사용량의 상관계수는 얼마인가요?
80
연면적이 1,000㎡ 이상인 건물 중, 2023년 에너지 소비 효율(사용량/면적)이 가장 낮은 건물은 어디인가요?
81
대구시 전체에서 건축물 층수와 에너지 사용량 사이의 상관관계를 수치로 분석해주세요.
82
대구시 동 중 2023년 여름(6~8월) 전기 사용량 증가율이 가장 높은 상위 10개 동을 시각화해주세요.
83
2023년 기준, 대구시 동별 1인당 지역난방 사용량이 평균보다 높은 곳만 필터링해서 보여주세요.
84
건물 용도, 층수, 에너지 사용량을 기준으로 군집화한 후, 각 군집별 평균 인구 수를 비교해주세요.
85
대구시에서 전기 사용량 상위 5% 건물 중, 동일 동 내 인구수가 평균 이하인 경우는 몇 건인가요?
86
2023년 기준으로 대구시에서 에너지 소비량 상위 동과 하위 동의 평균 건축 연도 차이를 알려주세요.
87
대구시 내 구별로 상업시설의 평균 전기 사용량을 비교한 테이블을 보여주세요.
88
건축물 수, 인구 수, 에너지 소비량 세 항목 기준으로 Z-score를 구해, 표준화된 동별 순위를 계산해주세요.
89
2023년 동별로 도시가스 사용량의 표준편차가 가장 큰 동 5개는 어디인가요?
90
대구시에서 2023년 에너지 사용량이 많은 동이 인구 증가율도 높은 경향이 있는지 분석해주세요.
91
대구시 동 중에서 2023년 1월과 8월의 전기 사용량 차이가 가장 큰 지역은 어디인가요?
92
대구시에서 동별 평균 건축물 층수와 평균 전기 사용량 간의 관계를 시각화해주세요.
93
인구 1인당 건물 면적이 가장 넓은 동의 2023년 에너지 사용량은 평균보다 높나요?
94
대구시 동별로 건축물 수 대비 인구 수 비율이 높은 지역과 에너지 사용량 간의 관계를 분석해주세요.
95
2023년 한 해 동안 에너지 사용량 변동이 가장 일정한(표준편차 가장 낮은) 동은 어디인가요?
96
2023년 대구시에서 전기, 도시가스, 지역난방 3종 모두 사용하는 건물의 평균 에너지 사용량을 분석해주세요.
97
대구시 동별 건축물 용도 다변성과 에너지 사용량 분산의 관계를 통계적으로 분석해주세요.
98
건물 수, 총 연면적, 에너지 사용량, 인구를 기준으로 동별 종합 에너지 효율 등급을 산정해주세요.
99

In [ ]:
# prompt: output_list output csv로

output_df = pd.DataFrame({'SQL_Query': output_list})
output_df.to_csv('output_mini.csv', index=False, encoding='utf-8-sig')

In [ ]:
output_list

["```sql\nSELECT * FROM building WHERE 면적 >= 10000 AND 지번주소 LIKE '대구광역시%';\n```",
 "```sql\nSELECT b.*\nFROM building b\nWHERE b.용도 = '업무시설' \nAND b.지번주소 LIKE '%대구광역시 수성구%'\nAND b.사용승인일 IS NOT NULL;\n```",
 "```sql\nSELECT *\nFROM building\nWHERE 도로명주소 LIKE '%대구시 동구%'\nAND 용도 LIKE '%지역난방%';\n```",
 "```sql\nSELECT * FROM building WHERE 지하층수 >= 2 AND 지번주소 LIKE '대구광역시%';\n```",
 "```sql\nSELECT COUNT(*) AS 건물_개수\nFROM building\nWHERE 도로명주소 LIKE '대구광역시 북구%'\nAND 사용승인일 BETWEEN '20220101' AND '20221231';\n```",
 "```sql\nSELECT * \nFROM building \nWHERE 지상층수 >= 3 AND 용도 LIKE '%교육시설%' AND 지번주소 LIKE '%대구 달성군%';\n```",
 "```sql\nSELECT * \nFROM building \nWHERE 사용승인일 <= strftime('%Y%m%d', 'now', '-10 years') \nAND 지번주소 LIKE '대구광역시%';\n```",
 "```sql\nSELECT DISTINCT b.*\nFROM building b\nJOIN electricity e ON b.pnu = e.pnu\nWHERE b.지번주소 LIKE '대구광역시 중구%'\nAND e.전기사용량 > 0;\n```",
 "```sql\nSELECT pnu \nFROM building \nWHERE 지번주소 LIKE '대구광역시 수성구 범어동%' \nAND 사용승인일 > '2010-12-31';\n```",
 "```sql\nSELECT * FROM building WHERE 지상층수 >= 5 AND 용도 = '업무시설';\n```",
 "```sql\nSELECT 용도, COUNT(*) AS 건물수\nFROM building\nWHERE 지번주소 LIKE '대구광역시%'\nGROUP BY 용도;\n```",
 "```sql\nSELECT SUBSTR(b.지번주소, INSTR(b.지번주소, ' ') + 1, INSTR(b.지번주소, ' ', INSTR(b.지번주소, ' ') + 1) - INSTR(b.지번주소, ' ') - 1) AS 자치구,\n       AVG(b.면적) AS 평균_연면적\nFROM building b\nWHERE b.지번주소 LIKE '대구광역시%'\nGROUP BY 자치구;\n```",
 "```sql\nSELECT b.*\nFROM building b\nJOIN gas g ON b.pnu = g.pnu\nWHERE b.도로명주소 LIKE '대구%'\nAND g.사용년월 = 202401\nORDER BY g.가스사용량 DESC\nLIMIT 10;\n```",
 "```sql\nSELECT AVG(전기사용량) AS 평균전기사용량 \nFROM electricity \nWHERE 지번주소 LIKE '대구광역시 중구%' AND 사용년월 BETWEEN 202201 AND 202212;\n```",
 "```sql\nSELECT SUBSTR(지번주소, INSTR(지번주소, ' ') + 1, INSTR(지번주소, ' ', INSTR(지번주소, ' ') + 1) - INSTR(지번주소, ' ') - 1) AS 구,\n       SUM(전기사용량) AS 전력_사용량_합계\nFROM electricity\nWHERE 지번주소 LIKE '대구광역시%'\nGROUP BY 구\nORDER BY 전력_사용량_합계 DESC;\n```",
 "```sql\nSELECT SUBSTR(지번주소, INSTR(지번주소, ' ') + 1) AS 동, \n       AVG(전기사용량) AS 평균전기사용량, \n       MAX(전기사용량) AS 최대전기사용량\nFROM electricity\nWHERE 사용년월 BETWEEN 202301 AND 202312\nGROUP BY 동;\n```",
 "```sql\nSELECT \n    '전기' AS 에너지원, \n    SUM(전기사용량) AS 총_사용량\nFROM electricity\nWHERE 지번주소 LIKE '대구%'\nGROUP BY 에너지원\n\nUNION ALL\n\nSELECT \n    '가스' AS 에너지원, \n    SUM(가스사용량) AS 총_사용량\nFROM gas\nWHERE 지번주소 LIKE '대구%'\nGROUP BY 에너지원;\n```",
 "```sql\nSELECT 지번주소, COUNT(*) AS 공동주택 수\nFROM building\nWHERE 용도 LIKE '%공동주택%'\nGROUP BY 지번주소\nORDER BY 공동주택 수 DESC\nLIMIT 1;\n```",
 "```sql\nSELECT b.용도, \n       AVG(e.전기사용량 + g.가스사용량) AS 평균_에너지_사용량, \n       STRFTIME('%Y-%m-%d', '2023-12-31') AS 기준일, \n       STDEV(e.전기사용량 + g.가스사용량) AS 표준편차\nFROM building b\nJOIN electricity e ON b.pnu = e.pnu\nJOIN gas g ON b.pnu = g.pnu\nWHERE b.지번주소 LIKE '대구광역시%'\nGROUP BY b.용도;\n```",
 "```sql\nSELECT 지상층수, COUNT(*) AS 건물수\nFROM building\nWHERE 지번주소 LIKE '대구광역시%'\nGROUP BY 지상층수;\n```",
 "```sql\nSELECT 지번주소\nFROM building\nWHERE 면적 >= 3000\nAND pnu IN (\n    SELECT pnu\n    FROM population\n    WHERE CAST(2023년_총인구수 AS INTEGER) >= 50000\n    AND 지번주소 LIKE '대구광역시%'\n)\nGROUP BY 지번주소\nORDER BY COUNT(*) DESC\nLIMIT 1;\n```",
 "```sql\nSELECT p.지번주소\nFROM electricity e\nJOIN population p ON e.pnu = p.pnu\nWHERE e.전기사용량 / p.2023년_총인구수 > (SELECT AVG(e2.전기사용량 / p2.2023년_총인구수)\n                                                   FROM electricity e2\n                                                   JOIN population p2 ON e2.pnu = p2.pnu\n                                                   WHERE p2.지번주소 LIKE '대구광역시 동구%')\nGROUP BY p.지번주소;\n```",
 "```sql\nSELECT p.지번주소, \n       SUM(e.전기사용량) / NULLIF(SUM(p.2023년_총인구수), 0) AS 전기_사용량_per_인구\nFROM population p\nJOIN electricity e ON p.pnu = e.pnu\nWHERE p.지번주소 LIKE '%대구광역시 남구%'\nGROUP BY p.지번주소\nORDER BY 전기_사용량_per_인구 DESC\nLIMIT 1;\n```",
 '```sql\nSELECT AVG(e.전기사용량 + g.가스사용량) AS 평균_에너지_소비량\nFROM population p\nJOIN building b ON p.pnu = b.pnu\nJOIN electricity e ON b.pnu = e.pnu AND p.지번주소 = e.지번주소\nJOIN gas g ON b.pnu = g.pnu AND p.지번주소 = g.지번주소\nWHERE b.용도 LIKE \'%업무%\' AND p."2023년_세대당 인구" > (SELECT AVG("2023년_세대당 인구") FROM population WHERE 지번주소 LIKE \'%대구시%\');\n```',
 "```sql\nSELECT AVG(e.전기사용량) AS 평균_세대당_사용량 \nFROM electricity e\nJOIN building b ON e.pnu = b.pnu\nWHERE b.용도 = '공동주택' \nAND b.지번주소 LIKE '대구광역시 달서구%';\n```",
 "```sql\nSELECT 법정동코드PNU\nFROM building\nWHERE 면적 >= 2000 AND 지번주소 LIKE '대구광역시 동구%'\nGROUP BY 법정동코드PNU\nHAVING COUNT(*) > 0\nORDER BY (SELECT SUM(CAST(2023년_총인구수 AS INTEGER)) FROM population WHERE 법정동코드PNU = building.법정동코드PNU) ASC\nLIMIT 1;\n```",
 '```sql\nSELECT p.지번주소, \n       SUM(e.전기사용량) / SUM(p."2023년_세대수") AS 1인당_전기_사용량, \n       AVG(b.면적) AS 평균_건축_연면적\nFROM electricity e\nJOIN population p ON e.지번주소 = p.지번주소\nJOIN building b ON p.pnu = b.pnu\nWHERE e.지번주소 LIKE \'대구광역시%\'\nGROUP BY p.지번주소\nORDER BY 1인당_전기_사용량 DESC\nLIMIT 1;\n```',
 "```sql\nSELECT DISTINCT p.지번주소\nFROM population p\nJOIN gas g ON p.pnu = g.pnu\nWHERE p.2023년_총인구수 >= '10000' \nAND g.가스사용량 >= (SELECT AVG(가스사용량) FROM gas WHERE 지번주소 LIKE '대구광역시 북구%')\nAND p.지번주소 LIKE '대구광역시 북구%'\n;",
 '```sql\nSELECT b.지번주소, \n       SUM(e.전기사용량 + g.가스사용량) / CAST(p.2023년_총인구수 AS NUMBER) AS 1인당_에너지_소비량\nFROM building b\nJOIN electricity e ON b.pnu = e.pnu\nJOIN gas g ON b.pnu = g.pnu\nJOIN population p ON b.pnu = p.pnu\nWHERE b.지하층수 = 0 AND b.법정동코드PNU = 271100\nGROUP BY b.지번주소;\n```',
 '```sql\nSELECT p.지번주소, p."2023년_세대당 인구", e.전기사용량, g.가스사용량\nFROM population p\nJOIN electricity e ON p.pnu = e.pnu\nJOIN gas g ON p.pnu = g.pnu\nWHERE p.지번주소 LIKE \'대구광역시 중구%\'\nAND p."2023년_세대당 인구" > (SELECT AVG("2023년_세대당 인구") FROM population WHERE 지번주소 LIKE \'대구광역시 중구%\')\nAND (e.전기사용량 + g.가스사용량) < (SELECT AVG(전기사용량 + 가스사용량) FROM electricity e2 JOIN gas g2 ON e2.pnu = g2.pnu WHERE e2.지번주소 LIKE \'대구광역시 중구%\')\nORDER BY p."2023년_세대당 인구" DESC;\n```',
 "```sql\nSELECT b.지번주소, e.전기사용량\nFROM electricity e\nJOIN building b ON e.pnu = b.pnu\nWHERE e.사용년월 BETWEEN 202301 AND 202312\n  AND b.지번주소 LIKE '대구광역시%'\nORDER BY e.전기사용량 DESC\nLIMIT 10;\n```",
 "```sql\nSELECT 용도 \nFROM gas g\nJOIN building b ON g.pnu = b.pnu\nWHERE g.사용년월 = 202301 AND b.지번주소 LIKE '대구광역시 중구 삼덕동%'\nGROUP BY b.용도\nORDER BY SUM(g.가스사용량) DESC\nLIMIT 1;\n```",
 "```sql\nSELECT COUNT(DISTINCT b.pnu) AS commercial_building_count\nFROM electricity e\nJOIN building b ON e.pnu = b.pnu\nWHERE b.용도 = '상업용' AND e.사용년월 BETWEEN 202301 AND 202312\nAND e.전기사용량 > (SELECT AVG(e2.전기사용량)\n                     FROM electricity e2 \n                     WHERE e2.사용년월 BETWEEN 202301 AND 202312 \n                     AND e2.pnu = e.pnu)\nGROUP BY e.pnu\nHAVING COUNT(e.전기사용량) > 1;\n```",
 "```sql\nSELECT b.지번주소, b.도로명주소 \nFROM building b\nJOIN electricity e ON b.pnu = e.pnu\nWHERE b.사용승인일 < '2000-01-01'\nAND e.사용년월 = 202401\nAND e.전기사용량 >= (\n    SELECT AVG(e2.전기사용량)\n    FROM electricity e2\n    WHERE e2.사용년월 = 202401\n)\nGROUP BY b.지번주소, b.도로명주소;\n```",
 "```sql\nSELECT b.용도\nFROM building b\nJOIN gas g ON b.pnu = g.pnu\nWHERE b.지번주소 LIKE '%수성구 범어동%' AND g.사용년월 == 2023\nORDER BY g.가스사용량 DESC\nLIMIT 1;\n```",
 "```sql\nSELECT COUNT(DISTINCT b.pnu) AS 증가한_건물수\nFROM electricity e1\nJOIN electricity e2 ON e1.pnu = e2.pnu\nJOIN building b ON e1.pnu = b.pnu\nWHERE b.지번주소 LIKE '%대명동%'\nAND e1.사용년월 = 202201\nAND e2.사용년월 = 202301\nAND e2.전기사용량 > e1.전기사용량 * 1.2;\n```",
 "```sql\nSELECT b.용도, AVG(g.가스사용량) AS 평균_가스사용량\nFROM gas g\nJOIN building b ON g.pnu = b.pnu\nWHERE g.사용년월 = 202301\nAND g.지번주소 LIKE '대구%'\nGROUP BY b.용도\nORDER BY 평균_가스사용량 DESC;\n```",
 "```sql\nSELECT b.지번주소, b.도로명주소, b.지상층수, e.전기사용량\nFROM building b\nJOIN electricity e ON b.pnu = e.pnu\nWHERE b.지상층수 >= 10 \n  AND e.전기사용량 > (SELECT MAX(전기사용량) * 0.95 FROM electricity WHERE 지번주소 LIKE '대구광역시%');\n```",
 "```sql\nSELECT b.pnu\nFROM building b\nJOIN electricity e ON b.pnu = e.pnu\nJOIN gas g ON b.pnu = g.pnu\nWHERE b.지번주소 LIKE '%달서구%'\nGROUP BY b.pnu\nORDER BY SUM(e.전기사용량 + g.가스사용량) DESC\nLIMIT 1;\n```",
 "```sql\nSELECT\n    p.지번주소,\n    CASE\n        WHEN e.전기사용량 > g.가스사용량 THEN '전기'\n        WHEN g.가스사용량 > e.전기사용량 THEN '가스'\n        ELSE '전기와 가스 동일 사용'\n    END AS 주 사용 에너지원\nFROM \n    population p\nLEFT JOIN \n    electricity e ON p.지번주소 = e.지번주소\nLEFT JOIN \n    gas g ON p.지번주소 = g.지번주소\nGROUP BY \n    p.지번주소;\n```",
 '```sql\nSELECT p.지번주소, AVG(e.전기사용량 / NULLIF(p."2023년_총인구수", 0)) AS 평균전기사용량\nFROM population p\nJOIN electricity e ON p.pnu = e.pnu\nWHERE e.사용년월 = 202301\nGROUP BY p.지번주소\nORDER BY 평균전기사용량 DESC\nLIMIT 1;\n```',
 '```sql\nSELECT 지번주소, MAX(가스사용량 / (SELECT "2023년_세대수" FROM population WHERE population.pnu = gas.pnu)) AS 1인당_가스사용량\nFROM gas\nJOIN population ON gas.pnu = population.pnu\nWHERE 지번주소 LIKE \'%수성구%\'\nGROUP BY 지번주소\nORDER BY 1인당_가스사용량 DESC\nLIMIT 1;\n```',
 '```sql\nSELECT AVG(e.전기사용량) AS 평균_전기사용량, AVG(g.가스사용량) AS 평균_가스사용량\nFROM population p\nJOIN gas g ON p.지번주소 = g.지번주소\nJOIN electricity e ON p.지번주소 = e.지번주소\nWHERE p.2023년_총인구수 IS NOT NULL AND p.2024년_총인구수 IS NOT NULL \nAND CAST(SUBSTR(p."2023년_남자 인구수", 1, INSTR(p."2023년_남자 인구수", \',\') - 1) AS INTEGER) + \n         CAST(SUBSTR(p."2023년_여자 인구수", 1, INSTR(p."2023년_여자 인구수", \',\') - 1) AS INTEGER) > 0\nAND (CAST(SUBSTR(p."2023년_남자 인구수", 1, INSTR(p."2023년_남자 인구수", \',\') - 1) AS INTEGER) + \n         CAST(SUBSTR(p."2023년_여자 인구수", 1, INSTR(p."2023년_여자 인구수", \',\') - 1) AS INTEGER) \n         - CAST(SUBSTR(p."2023년_총인구수", 1, INSTR(p."2023년_총인구수", \',\') - 1) AS INTEGER)) / \n         CAST(SUBSTR(p."2023년_총인구수", 1, INSTR(p."2023년_총인구수", \',\') - 1) AS INTEGER) > 0.2\nAND p.지번주소 LIKE \'대구광역시 중구%\';\n```',
 '```sql\nSELECT \n    p.지번주소, \n    p."2023년_총인구수", \n    p."2023년_세대당 인구", \n    e.전기사용량, \n    g.가스사용량\nFROM \n    population p\nJOIN \n    electricity e ON p.pnu = e.pnu\nJOIN \n    gas g ON p.pnu = g.pnu\nWHERE \n    p.지번주소 LIKE \'대구광역시%\'\nORDER BY \n    p.지번주소;\n```',
 "```sql\nSELECT p.지번주소, \n       SUM(e.전기사용량) / NULLIF(SUM(p.2023년_총인구수), 0) AS 전기_사용량_퍼_인구\nFROM population p\nJOIN electricity e ON p.pnu = e.pnu\nWHERE p.지번주소 LIKE '대구광역시 중구%'\nGROUP BY p.지번주소;\n```",
 '```sql\nSELECT p.지번주소, \n       SUM(e.전기사용량 + g.가스사용량) / SUM(b.면적) AS 에너지소비량\nFROM population p\nJOIN building b ON p.pnu = b.pnu\nJOIN electricity e ON b.pnu = e.pnu\nJOIN gas g ON b.pnu = g.pnu\nGROUP BY p.지번주소\nORDER BY 에너지소비량 DESC\nLIMIT 1;\n```',
 '```sql\nSELECT \n    p.지번주소, \n    p."2023년_총인구수", \n    p."2023년_세대당 인구",\n    e.전기사용량, \n    g.가스사용량\nFROM \n    population p\nJOIN \n    electricity e ON p.pnu = e.pnu \nJOIN \n    gas g ON p.pnu = g.pnu\nWHERE \n    p.지번주소 LIKE \'대구광역시%\' \n    AND p."2023년_총인구수" NOT LIKE \'%[0-9]%\'  -- Assuming foreign population is expressed in non-numeric format\nORDER BY \n    p."2023년_총인구수" DESC;\n```',
 "```sql\nSELECT AVG(g.가스사용량) AS 평균_도시가스_사용량\nFROM gas g\nJOIN population p ON g.지번주소 = p.지번주소\nWHERE p.법정동코드PNU = (SELECT 법정동코드PNU FROM building WHERE 도로명주소 LIKE '%달서구%')\nAND p.2023년_총인구수 > 1000; \n```",
 '```sql\nSELECT \n    p.지번주소,\n    p."2023년_총인구수",\n    p."2023년_세대수",\n    e.전기사용량,\n    g.가스사용량\nFROM \n    population p\nLEFT JOIN \n    electricity e ON p.지번주소 = e.지번주소\nLEFT JOIN \n    gas g ON p.지번주소 = g.지번주소\nWHERE \n    p.지번주소 LIKE \'%수성구%\' OR p.지번주소 LIKE \'%북구%\'\nORDER BY \n    p.지번주소, e.사용년월;\n```',
 '```sql\nSELECT \n    p.지번주소,\n    SUM(g.가스사용량) / NULLIF(SUM(p."2023년_총인구수"), 0) AS "1인당 지역난방 사용량"\nFROM \n    population p\nJOIN \n    gas g ON p.pnu = g.pnu\nWHERE \n    g.사용년월 = 202401\nGROUP BY \n    p.지번주소\nORDER BY \n    "1인당 지역난방 사용량" DESC;\n```',
 '```sql\nSELECT 지번주소,\n       ((SUM(CASE WHEN 사용년월 BETWEEN 202001 AND 202012 THEN 전기사용량 END) -\n         SUM(CASE WHEN 사용년월 BETWEEN 202101 AND 202112 THEN 전기사용량 END)) /\n         NULLIF(SUM(CASE WHEN 사용년월 BETWEEN 202101 AND 202112 THEN 전기사용량 END), 0)) * 100 AS 전기_증가율,\n       ((SUM(CASE WHEN 사용년월 BETWEEN 202001 AND 202012 THEN 가스사용량 END) -\n         SUM(CASE WHEN 사용년월 BETWEEN 202101 AND 202112 THEN 가스사용량 END)) /\n         NULLIF(SUM(CASE WHEN 사용년월 BETWEEN 202101 AND 202112 THEN 가스사용량 END), 0)) * 100 AS 가스_증가율\nFROM electricity\nJOIN gas ON electricity.지번주소 = gas.지번주소 AND electricity.사용년월 = gas.사용년월\nGROUP BY 지번주소\nORDER BY (전기_증가율 + 가스_증가율) DESC\nLIMIT 1;\n```',
 "```sql\nSELECT \n    SUBSTR(지번주소, INSTR(지번주소, ' ') + 1, INSTR(지번주소, ' ', INSTR(지번주소, ' ') + 1) - INSTR(지번주소, ' ') - 1) AS 동,\n    사용년월,\n    SUM(전기사용량) AS 총전기사용량\nFROM \n    electricity\nWHERE \n    사용년월 BETWEEN 202401 AND 202403\nGROUP BY \n    동, 사용년월\nORDER BY \n    동, 사용년월;\n```",
 '```sql\nSELECT DISTINCT 지번주소\nFROM gas\nGROUP BY 지번주소, 사용년월\nHAVING COUNT(DISTINCT 사용년월) >= 3\nAND SUM(가스사용량) > 0\nORDER BY 지번주소;\n```',
 '```sql\nSELECT g1.지번주소\nFROM gas g1\nJOIN gas g2 ON g1.지번주소 = g2.지번주소\nWHERE g1.사용년월 = 202201 AND g2.사용년월 = 202301\nAND g1.가스사용량 > g2.가스사용량;\n```',
 "```sql\nSELECT 사용년월, MAX(전기가용량) AS 피크전기사용량\nFROM electricity\nWHERE 도로명주소 LIKE '%상업시설%' AND 사용년월 BETWEEN 202306 AND 202309\nGROUP BY 사용년월\nORDER BY 피크전기사용량 DESC\nLIMIT 1;\n```",
 "```sql\nSELECT\n    SUBSTR(사용년월, 1, 6) AS 년월,\n    AVG(전기사용량) AS 월평균전기사용량,\n    b.법정동코드PNU\nFROM\n    electricity e\nJOIN\n    building b ON e.pnu = b.pnu\nWHERE\n    SUBSTR(사용년월, 1, 4) = '2023'\nGROUP BY\n    SUBSTR(사용년월, 1, 6), b.법정동코드PNU\nORDER BY\n    년월;\n```",
 "```sql\nSELECT 사용년월, SUM(전기사용량) AS 총전기사용량, SUM(가스사용량) AS 총가스사용량\nFROM electricity\nJOIN gas ON electricity.지번주소 = gas.지번주소 AND electricity.사용년월 = gas.사용년월\nWHERE electricity.지번주소 LIKE '대구%'\nGROUP BY 사용년월\nORDER BY 사용년월;\n```",
 '```sql\nSELECT b.*\nFROM electricity e\nJOIN building b ON e.pnu = b.pnu\nWHERE e.사용년월 IN (202301, 202308) \nGROUP BY b.pnu\nHAVING SUM(CASE WHEN e.사용년월 = 202301 THEN e.전기사용량 ELSE 0 END) > \n           (SELECT AVG(e2.전기사용량) FROM electricity e2 WHERE e2.사용년월 = 202301) \n   AND SUM(CASE WHEN e.사용년월 = 202308 THEN e.전기사용량 ELSE 0 END) > \n           (SELECT AVG(e3.전기사용량) FROM electricity e3 WHERE e3.사용년월 = 202308);\n```',
 "```sql\nSELECT 지번주소, MAX(전기사용량) - MIN(전기사용량) AS 전기사용량_변동성\nFROM electricity\nWHERE 지번주소 LIKE '대구광역시%'\nGROUP BY 지번주소\nORDER BY 전기사용량_변동성 DESC\nLIMIT 1;\n```",
 '```sql\nSELECT \n    e.사용년월,\n    AVG(e.전기사용량) AS 평균전기사용량,\n    AVG(g.가스사용량) AS 평균가스사용량\nFROM \n    electricity e\nJOIN \n    gas g ON e.지번주소 = g.지번주소 AND e.사용년월 = g.사용년월\nGROUP BY \n    e.사용년월\nORDER BY \n    e.사용년월;\n```',
 "```sql\nSELECT b.지번주소 \nFROM building b\nJOIN population p ON b.pnu = p.pnu\nJOIN gas g ON b.pnu = g.pnu\nWHERE b.지번주소 LIKE '대구광역시%'\nGROUP BY b.지번주소\nHAVING COUNT(b.pnu) >= 100 \n   AND (SUM(g.가스사용량) / SUM(p.2023년_세대수)) >= \n       (SELECT AVG(SUM(g2.가스사용량) / SUM(p2.2023년_세대수)) \n        FROM building b2 \n        JOIN population p2 ON b2.pnu = p2.pnu \n        JOIN gas g2 ON b2.pnu = g2.pnu \n        WHERE b2.지번주소 LIKE '대구광역시%' \n        GROUP BY b2.지번주소);\n```",
 '```sql\nSELECT b.지번주소, b.도로명주소, b.면적, e.전기사용량, g.가스사용량\nFROM building b\nJOIN electricity e ON b.pnu = e.pnu AND e.사용년월 = 202301\nJOIN gas g ON b.pnu = g.pnu AND g.사용년월 = 202301\nWHERE b.면적 >= 5000 AND (e.전기사용량 + g.가스사용량) >= (\n    SELECT AVG(e2.전기사용량 + g2.gas사용량)\n    FROM electricity e2\n    JOIN gas g2 ON e2.pnu = g2.pnu\n    WHERE e2.사용년월 = 202301\n);\n```',
 "```sql\nSELECT b.지번주소, e.전기사용량\nFROM building b\nJOIN electricity e ON b.pnu = e.pnu\nWHERE b.지상층수 >= 15 AND b.지번주소 LIKE '%수성구%'\nORDER BY e.전기사용량 ASC\nLIMIT 10;\n```",
 "```sql\nSELECT 용도, SUM(전기사용량) / SUM(면적) AS 에너지효율\nFROM electricity e\nJOIN building b ON e.pnu = b.pnu\nWHERE b.지번주소 LIKE '대구광역시%'\nGROUP BY 용도\nORDER BY 에너지효율 DESC\nLIMIT 1;\n```",
 '```sql\nSELECT e.지번주소, SUM(e.전기사용량) AS 총전기사용량, p.2023년_총인구수, p.2024년_총인구수\nFROM electricity e\nJOIN population p ON e.pnu = p.pnu\nWHERE e.사용년월 = 202401\nGROUP BY e.지번주소\nHAVING SUM(e.전기사용량) > (SELECT SUM(전기사용량) FROM electricity WHERE 사용년월 = 202312 AND pnu = e.pnu)\nAND (CAST(p.2024년_총인구수 AS INTEGER) > CAST(p.2023년_총인구수 AS INTEGER));\n```',
 '```sql\nSELECT \n    p.지번주소,\n    AVG(e.전기사용량) AS 평균_전기_사용량,\n    AVG(CASE WHEN b.사용승인일 IS NOT NULL THEN CAST(SUBSTR(b.사용승인일, 1, 4) AS INTEGER) ELSE NULL END) AS 평균_건축연도\nFROM \n    population p\nLEFT JOIN \n    electricity e ON p.지번주소 = e.지번주소 AND e.사용년월 BETWEEN 202301 AND 202312\nLEFT JOIN \n    building b ON p.pnu = b.pnu\nGROUP BY \n    p.지번주소;\n```',
 '```sql\nSELECT\n    b.지번주소,\n    AVG(e.전기사용량) AS 평균_전기사용량,\n    COALESCE(p."2023년_총인구수", 0) AS 총인구수,\n    COALESCE(SUM(e.전기사용량) / NULLIF(p."2023년_총인구수",0), 0) AS 인구당_평균_전기사용량\nFROM\n    building b\nLEFT JOIN\n    electricity e ON b.pnu = e.pnu\nLEFT JOIN\n    population p ON b.pnu = p.pnu\nWHERE\n    b.지번주소 LIKE \'대구%\'\nGROUP BY\n    b.지번주소;\n```',
 "```sql\nSELECT \n    b.용도,\n    SUM(e.전기사용량) AS 총전기사용량,\n    SUM(g.가스사용량) AS 총가스사용량,\n    CASE \n        WHEN SUM(g.가스사용량) = 0 THEN 0\n        ELSE SUM(e.전기사용량) / SUM(g.가스사용량)\n    END AS 전기_가스_비율\nFROM \n    building b\nJOIN \n    electricity e ON b.pnu = e.pnu\nJOIN \n    gas g ON b.pnu = g.pnu\nWHERE \n    b.용도 = '주거용' AND \n    (b.지번주소 LIKE '%달서구%' OR b.지번주소 LIKE '%달성군%')\nGROUP BY \n    b.용도;\n```",
 "```sql\nSELECT \n    b.용도, \n    SUM(e.전기사용량) AS 총전기사용량, \n    SUM(g.가스사용량) AS 총가스사용량\nFROM \n    building b\nLEFT JOIN \n    electricity e ON b.pnu = e.pnu\nLEFT JOIN \n    gas g ON b.pnu = g.pnu\nWHERE \n    b.지번주소 LIKE '대구%' \nGROUP BY \n    b.용도;\n```",
 '```sql\nSELECT DISTINCT e.지번주소\nFROM electricity e\nJOIN population p ON e.pnu = p.pnu\nWHERE e.사용년월 = 202401\nORDER BY e.전기사용량 DESC\nLIMIT 10\nINTERSECT\nSELECT DISTINCT p.지번주소\nFROM population p\nWHERE p."2023년_세대당 인구" IS NOT NULL\nORDER BY p."2023년_세대당 인구" DESC\nLIMIT 10;\n```',
 '```sql\nSELECT p.지번주소, AVG(e.전기사용량 / NULLIF(p."2023년_세대수", 0)) AS 1인당_전기_사용량\nFROM population p\nJOIN electricity e ON p.지번주소 = e.지번주소 AND e.사용년월 = 202301\nWHERE CAST(REPLACE(p.2023년_총인구수, \',\', \'\') AS INTEGER) >= 5000\nGROUP BY p.지번주소\nORDER BY 1인당_전기_사용량 DESC\nLIMIT 5;\n```',
 '```sql\nSELECT b.지번주소, SUM(b.면적) AS 총면적, SUM(g.가스사용량) AS 총가스사용량,\n       (SUM(g.가스사용량) / SUM(b.면적)) AS 사용량비율\nFROM building b\nJOIN gas g ON b.pnu = g.pnu\nWHERE g.사용년월 = 202401\nGROUP BY b.지번주소\nORDER BY 사용량비율 DESC\nLIMIT 1;\n```',
 "```sql\nSELECT \n    SUBSTR(b.지번주소, INSTR(b.지번주소, ' ') + 1) AS 동,\n    AVG(e.전기사용량) AS 평균_전기사용량,\n    AVG(g.가스사용량) AS 평균_가스사용량\nFROM \n    building b\nJOIN \n    electricity e ON b.pnu = e.pnu\nJOIN \n    gas g ON b.pnu = g.pnu AND e.사용년월 = g.사용년월\nWHERE \n    b.사용승인일 < '1990-01-01'\nGROUP BY \n    동;\n```",
 "```sql\nSELECT \n    b.용도 || '+' || CASE WHEN b.지상층수 >= 10 THEN '10층 이상' ELSE '10층 미만' END AS 용도_층수,\n    AVG(e.전기사용량) AS 평균전기사용량\nFROM \n    building b\nJOIN \n    electricity e ON b.pnu = e.pnu\nWHERE \n    b.지번주소 LIKE '대구광역시%'\nGROUP BY \n    용도_층수;\n```",
 "```sql\nSELECT e.사용년월, SUM(e.전기사용량) AS 총전기사용량\nFROM electricity e\nJOIN building b ON e.pnu = b.pnu\nWHERE b.용도 LIKE '%상업%'\nGROUP BY e.사용년월\nHAVING COUNT(b.pnu) / (SELECT COUNT(*) FROM building WHERE b.법정동코드PNU = building.법정동코드PNU) >= 0.5;\n```",
 "```sql\nSELECT AVG(CAST(substr(사용승인일, 1, 4) AS INTEGER)) AS 평균_건축_연도\nFROM building\nWHERE pnu IN (\n    SELECT b.pnu\n    FROM building b\n    JOIN electricity e ON b.pnu = e.pnu\n    WHERE b.지번주소 LIKE '대구광역시%'\n    GROUP BY b.pnu\n    HAVING SUM(e.전기사용량) >= (\n        SELECT MIN(total_usage)\n        FROM (\n            SELECT SUM(e2.전기사용량) AS total_usage\n            FROM building b2\n            JOIN electricity e2 ON b2.pnu = e2.pnu\n            WHERE b2.지번주소 LIKE '대구광역시%'\n            GROUP BY b2.pnu\n            ORDER BY total_usage DESC\n            LIMIT (SELECT COUNT(*) FROM building WHERE 지번주소 LIKE '대구광역시%') * 0.1\n        )\n    )\n);\n```",
 '```sql\nSELECT 용도, AVG((전기사용량 - avg_usage) * (전기사용량 - avg_usage)) AS variance\nFROM (\n    SELECT b.용도, e.전기사용량, AVG(e.전기사용량) OVER (PARTITION BY b.용도) AS avg_usage\n    FROM building b\n    JOIN electricity e ON b.pnu = e.pnu\n    WHERE b.도로명주소 IS NOT NULL\n)\nGROUP BY 용도\nORDER BY variance DESC\nLIMIT 1;\n```',

In [ ]:
output_df['SQL_Query'][0]

'To retrieve the list of buildings in Daegu with a total area of 10,000 square meters or more, we need to query the `building` table. Assuming "연면적" refers to "면적" in the schema, we should filter the buildings with an area of at least 10,000 square meters. Here is the SQL query:\n\n```sql\nSELECT *\nFROM building\nWHERE CAST(면적 AS FLOAT) >= 10000;\n```\n\nNote: This query assumes that "면적" is stored in a format that can be converted to a float for comparison. If the data contains units or other non-numeric characters, you may need additional parsing logic. Also, ensure that the data in the "면적" column represents total area and is not misinterpreted.'

In [ ]:
# sql query 에서 extraction
import re

In [ ]:
import sqlite3
#3
# SQLite 데이터베이스 파일 연결
conn = sqlite3.connect("your_database.db")  # 파일명에 맞게 수정

# 커서 객체 생성
cursor = conn.cursor()
with engine.connect() as conn:
    result = conn.execute(text("""
WITH old_buildings AS (
    SELECT
        pnu,
        지번주소,
        SUBSTR(지번주소, 1, INSTR(지번주소, '동') + 1) AS 동
    FROM building
    WHERE
        지번주소 LIKE '대구%'
        AND CAST(SUBSTR(사용승인일, 1, 4) AS INTEGER) < 1990
),
energy_per_building AS (
    SELECT
        CAST(PNU AS TEXT) AS pnu,
        전기사용량
    FROM energy_usage
)
SELECT
    ob.동,
    AVG(e.전기사용량) AS 평균_전기사용량
FROM old_buildings ob
JOIN energy_per_building e ON ob.pnu = e.pnu
GROUP BY ob.동
ORDER BY 평균_전기사용량 DESC;

"""))
# 쿼리 정의


# 쿼리 실행
# cursor.execute(query)

In [ ]:
population.columns

Index(['행정구역', '2020년01월_총인구수', '2020년01월_세대수', '2020년01월_세대당 인구',
       '2020년01월_남자 인구수', '2020년01월_여자 인구수', '2020년01월_남여 비율', '2020년02월_총인구수',
       '2020년02월_세대수', '2020년02월_세대당 인구',
       ...
       '2024년11월_여자 인구수', '2024년11월_남여 비율', '2024년12월_총인구수', '2024년12월_세대수',
       '2024년12월_세대당 인구', '2024년12월_남자 인구수', '2024년12월_여자 인구수',
       '2024년12월_남여 비율', '시군구코드', '법정동코드'],
      dtype='object', length=363)

In [ ]:
population.shape

(172, 363)

In [ ]:
conn = sqlite3.connect("your_database.db")  # 파일명에 맞게 수정

# 커서 객체 생성
cursor = conn.cursor()
tables = cursor.fetchall()

print("테이블 목록:", tables)

테이블 목록: []

In [ ]:
inspector = inspect(engine)
schema_info = {}

tables = inspector.get_table_names()

In [ ]:
tables

['building', 'energy_usage']

In [ ]:
rows = result.fetchall()
# 출력
for row in rows:
    print(row)

(1978.6,)

In [ ]:
import sqlite3
#3번
# SQLite 데이터베이스 파일 연결
conn = sqlite3.connect("your_database.db")  # 파일명에 맞게 수정

# 커서 객체 생성
cursor = conn.cursor()
with engine.connect() as conn:
    result = conn.execute(text("""
WITH old_buildings AS (
  SELECT
    pnu,
    SUBSTR(지번주소, 1, INSTR(지번주소, '동') + 0) AS 동주소,
    CAST(SUBSTR(사용승인일, 1, 4) AS INTEGER) AS 건축연도
  FROM building
  WHERE LENGTH(사용승인일) >= 4
    AND CAST(SUBSTR(사용승인일, 1, 4) AS INTEGER) < 1990
),
filtered_energy AS (
  SELECT
    e.PNU,
    e.전기사용량,
    e.사용년월
  FROM energy_usage e
  WHERE 사용년월 BETWEEN 202301 AND 202312
),
joined_data AS (
  SELECT
    b.동주소,
    f.전기사용량
  FROM old_buildings b
  JOIN filtered_energy f ON b.pnu = f.PNU
)
SELECT
  동주소,
  ROUND(AVG(전기사용량), 1) AS 평균_전기사용량
FROM joined_data
GROUP BY 동주소
ORDER BY 평균_전기사용량 DESC;
"""))
# 쿼리 정의


# 쿼리 실행
# cursor.execute(query)

In [ ]:
rows = result.fetchall()
# 출력
for row in rows:
    print(row)

In [ ]:

#4번
import sqlite3

# SQLite 데이터베이스 파일 연결
conn = sqlite3.connect("your_database.db")  # 파일명에 맞게 수정

# 커서 객체 생성
cursor = conn.cursor()
with engine.connect() as conn:
    result = conn.execute(text("""WITH total_floors AS (
  SELECT
    pnu,
    용도,
    (지상층수 + 지하층수) AS 총층수
  FROM building
),
labeled_building AS (
  SELECT
    pnu,
    용도,
    CASE
      WHEN (지상층수 + 지하층수) >= 10 THEN '10층 이상'
      ELSE '10층 미만'
    END AS 층수범주
  FROM building
),
joined_data AS (
  SELECT
    lb.용도,
    lb.층수범주,
    e.전기사용량
  FROM labeled_building lb
  JOIN energy_usage e ON lb.pnu = e.PNU
  WHERE e.사용년월 BETWEEN 202301 AND 202312
)
SELECT
  용도,
  층수범주,
  ROUND(AVG(전기사용량), 2) AS 평균전기사용량
FROM joined_data
GROUP BY 용도, 층수범주
ORDER BY 평균전기사용량 DESC;"""))
# 쿼리 정의


# 쿼리 실행
# cursor.execute(query)

In [ ]:
rows = result.fetchall()
# 출력
for row in rows:
    print(row)

('창고시설', '10층 미만', 36713.67)
('단독주택', '10층 미만', 21448.72)
('동물및식물관련시설', '10층 미만', 3319.38)
('제1종근린생활시설', '10층 미만', 3177.96)
('공동주택', '10층 미만', 682.75)

In [ ]:

#5번
import sqlite3

# SQLite 데이터베이스 파일 연결
conn = sqlite3.connect("your_database.db")  # 파일명에 맞게 수정

# 커서 객체 생성
cursor = conn.cursor()
with engine.connect() as conn:
    result = conn.execute(text("""WITH building_with_dong AS (
  SELECT
    pnu,
    용도,
    -- 주소에서 시·구·동을 추출: 예) '대구광역시 중구 동인동'
    SUBSTR(지번주소, 1, INSTR(지번주소, '동') + 0) AS 동주소
  FROM building
  WHERE 지번주소 LIKE '%동%'
),
dong_total_counts AS (
  SELECT 동주소, COUNT(*) AS 전체건물수
  FROM building_with_dong
  GROUP BY 동주소
),
dong_commercial_counts AS (
  SELECT 동주소, COUNT(*) AS 상업용건물수
  FROM building_with_dong
  WHERE 용도 = '상업용'
  GROUP BY 동주소
),
dong_with_ratio AS (
  SELECT
    t.동주소,
    c.상업용건물수,
    t.전체건물수,
    1.0 * c.상업용건물수 / t.전체건물수 AS 상업용비율
  FROM dong_total_counts t
  JOIN dong_commercial_counts c ON t.동주소 = c.동주소
  WHERE 1.0 * c.상업용건물수 / t.전체건물수 >= 0.5
),
usage_with_dong AS (
  SELECT
    SUBSTR(e.지번주소, 1, INSTR(e.지번주소, '동') + 0) AS 동주소,
    e.사용년월,
    e.전기사용량
  FROM energy_usage e
),
filtered_usage AS (
  SELECT u.동주소, u.사용년월, u.전기사용량
  FROM usage_with_dong u
  JOIN dong_with_ratio d ON u.동주소 = d.동주소
  WHERE 사용년월 BETWEEN 202301 AND 202312
)
SELECT
  동주소,
  사용년월,
  SUM(전기사용량) AS 월별전기사용량
FROM filtered_usage
GROUP BY 동주소, 사용년월
ORDER BY 동주소, 사용년월;
"""))
# 쿼리 정의


# 쿼리 실행
# cursor.execute(query)

In [ ]:
rows = result.fetchall()
# 출력
for row in rows:
    print(row)

In [ ]:
#6
import sqlite3

# SQLite 데이터베이스 파일 연결
conn = sqlite3.connect("your_database.db")  # 파일명에 맞게 수정

# 커서 객체 생성
cursor = conn.cursor()
with engine.connect() as conn:
    result = conn.execute(text("""WITH usage_per_building AS (
  SELECT
    PNU,
    SUM(전기사용량) AS total_usage
  FROM energy_usage
  WHERE 사용년월 BETWEEN 202301 AND 202312
  GROUP BY PNU
),
top_10_buildings AS (
  SELECT PNU
  FROM usage_per_building
  ORDER BY total_usage DESC
  LIMIT 10  -- ✅ 필요 시 상위 N개로 직접 설정
),
build_years AS (
  SELECT
    b.사용승인일,
    CAST(SUBSTR(b.사용승인일, 1, 4) AS INTEGER) AS 건축연도
  FROM building b
  JOIN top_10_buildings t ON b.pnu = t.PNU
  WHERE LENGTH(b.사용승인일) >= 4
)
SELECT
  ROUND(AVG(건축연도), 1) AS 평균_건축연도
FROM build_years;
"""))
# 쿼리 정의


# 쿼리 실행
# cursor.execute(query)

In [ ]:
rows = result.fetchall()
# 출력
for row in rows:
    print(row)

(None,)

In [ ]:
#7
import sqlite3

# SQLite 데이터베이스 파일 연결
conn = sqlite3.connect("your_database.db")  # 파일명에 맞게 수정

# 커서 객체 생성
cursor = conn.cursor()
with engine.connect() as conn:
    result = conn.execute(text("""WITH usage_per_building AS (
  SELECT
    e.PNU,
    SUM(e.전기사용량) AS total_usage
  FROM energy_usage e
  WHERE e.사용년월 BETWEEN 202301 AND 202312
  GROUP BY e.PNU
),
usage_with_purpose AS (
  SELECT
    u.total_usage,
    b.용도
  FROM usage_per_building u
  JOIN building b ON u.PNU = b.pnu
),
variance_per_purpose AS (
  SELECT
    용도,
    COUNT(*) AS n,
    SUM(total_usage) * 1.0 AS sum_x,
    SUM(total_usage * total_usage) * 1.0 AS sum_x2,
    -- 분산 계산 공식 적용
    (SUM(total_usage * total_usage) * 1.0 / COUNT(*)) -
    ( (SUM(total_usage) * 1.0 / COUNT(*)) * (SUM(total_usage) * 1.0 / COUNT(*)) ) AS variance
  FROM usage_with_purpose
  GROUP BY 용도
)
SELECT 용도, ROUND(variance, 2) AS 분산
FROM variance_per_purpose
ORDER BY variance DESC
LIMIT 1;

"""))
# 쿼리 정의


# 쿼리 실행
# cursor.execute(query)

In [ ]:
rows = result.fetchall()
# 출력
for row in rows:
    print(row)

('단독주택', 23587598187.54)

In [ ]:
#8
import sqlite3

# SQLite 데이터베이스 파일 연결
conn = sqlite3.connect("your_database.db")  # 파일명에 맞게 수정

# 커서 객체 생성
cursor = conn.cursor()
with engine.connect() as conn:
    result = conn.execute(text("""WITH energy_with_dong AS (
  SELECT
    SUBSTR(지번주소, 1, INSTR(지번주소, '동') + 0) AS 동주소,
    사용년월,
    전기사용량
  FROM energy_usage
  WHERE 사용년월 BETWEEN 202201 AND 202312
),
dong_yearly_usage AS (
  SELECT
    동주소,
    CASE
      WHEN 사용년월 BETWEEN 202201 AND 202212 THEN '2022'
      WHEN 사용년월 BETWEEN 202301 AND 202312 THEN '2023'
    END AS 연도,
    SUM(전기사용량) AS 총사용량
  FROM energy_with_dong
  GROUP BY 동주소, 연도
),
pivot_usage AS (
  SELECT
    동주소,
    MAX(CASE WHEN 연도 = '2022' THEN 총사용량 END) AS 사용량_2022,
    MAX(CASE WHEN 연도 = '2023' THEN 총사용량 END) AS 사용량_2023
  FROM dong_yearly_usage
  GROUP BY 동주소
),
increased_dongs AS (
  SELECT
    동주소
  FROM pivot_usage
  WHERE 사용량_2022 IS NOT NULL AND 사용량_2023 IS NOT NULL
    AND 사용량_2023 >= 사용량_2022 * 1.2
)
SELECT
  COUNT(*) AS 증가한_동_수,
  GROUP_CONCAT(동주소, ', ') AS 증가한_동_목록
FROM increased_dongs;

"""))
# 쿼리 정의


# 쿼리 실행
# cursor.execute(query)

In [ ]:
rows = result.fetchall()
# 출력
for row in rows:
    print(row)

(0, None)

In [ ]:
#9
import sqlite3

# SQLite 데이터베이스 파일 연결
conn = sqlite3.connect("your_database.db")  # 파일명에 맞게 수정

# 커서 객체 생성
cursor = conn.cursor()
with engine.connect() as conn:
    result = conn.execute(text("""WITH energy_2023 AS (
  SELECT
    SUBSTR(지번주소, 1, INSTR(지번주소, '동') + 0) AS 동주소,
    사용년월,
    전기사용량
  FROM energy_usage
  WHERE 사용년월 BETWEEN 202301 AND 202312
),
ranked_usage AS (
  SELECT
    동주소,
    사용년월,
    전기사용량,
    RANK() OVER (PARTITION BY 동주소 ORDER BY 전기사용량 DESC) AS rn
  FROM energy_2023
)
SELECT
  동주소,
  사용년월 AS 피크월,
  전기사용량 AS 피크전기사용량
FROM ranked_usage
WHERE rn = 1
ORDER BY 피크전기사용량 DESC;


"""))
# 쿼리 정의


# 쿼리 실행
# cursor.execute(query)

In [ ]:
rows = result.fetchall()
# 출력
for row in rows:
    print(row)

('대구광역시 서구 평리동', 202310, 8642512)
('', 202307, 5912244)
('대구광역시 동', 202308, 4486339)
('대구광역시 북구 서변동', 202306, 4398945)
('대구광역시 북구 학정동', 202308, 3695254)
('대구광역시 달서구 신당동', 202308, 3549595)
('대구광역시 서구 비산동', 202307, 3448697)
('대구광역시 중구 계산동', 202308, 2959018)
('대구광역시 남구 대명동', 202308, 2745108)
('대구광역시 수성구 범어동', 202308, 2364648)
('대구광역시 북구 칠성동', 202308, 2156406)
('대구광역시 중구 삼덕동', 202308, 2080152)
('대구광역시 북구 동', 202301, 1970064)
('대구광역시 북구 매천동', 202308, 1713705)
('대구광역시 달서구 감삼동', 202308, 1626267)
('대구광역시 중구 대봉동', 202308, 1553562)
('대구광역시 수성구 두산동', 202308, 1482367)
('대구광역시 달서구 유천동', 202309, 1410267)
('대구광역시 북구 산격동', 202308, 1261536)
('대구광역시 북구 침산동', 202308, 1229736)
('대구광역시 서구 중리동', 202308, 1221762)
('대구광역시 달서구 월성동', 202309, 1196085)
('대구광역시 수성구 상동', 202309, 1186959)
('대구광역시 중구 덕산동', 202307, 1170871)
('대구광역시 달서구 용산동', 202308, 1120272)
('대구광역시 달서구 대천동', 202309, 1118746)
('대구광역시 수성구 황금동', 202308, 1093203)
('대구광역시 달서구 파호동', 202308, 1088789)
('대구광역시 수성구 만촌동', 202308, 1073239)
('대구광역시 달서구 상인동', 202307, 1042622)
('대구광역시 중구 남산동', 202308, 941570)
('대구광역시 북구 고성동', 202308, 938475)
('대구광역시 달서구 본리동', 202309, 823693)
('대구광역시 달서구 호산동', 202308, 814196)
('대구광역시 북구 태전동', 202308, 806147)
('대구광역시 서구 내당동', 202308, 802737)
('대구광역시 달서구 두류동', 202301, 800280)
('대구광역시 중구 수창동', 202309, 797411)
('대구광역시 수성구 수성동', 202309, 796155)
('대구광역시 달서구 도원동', 202309, 783931)
('대구광역시 북구 노원동', 202301, 781081)
('대구광역시 북구 복현동', 202308, 759471)
('대구광역시 수성구 대흥동', 202301, 753098)
('대구광역시 중구 대신동', 202308, 744855)
('대구광역시 달서구 대곡동', 202308, 723330)
('대구광역시 달서구 월암동', 202308, 716256)
('대구광역시 수성구 사월동', 202308, 704971)
('대구광역시 수성구 범물동', 202308, 674155)
('대구광역시 달서구 이곡동', 202308, 647438)
('대구광역시 서구 이현동', 202305, 634752)
('대구광역시 북구 관음동', 202308, 633023)
('대구광역시 북구 사수동', 202309, 631185)
('대구광역시 달서구 장기동', 202308, 628078)
('대구광역시 남구 봉덕동', 202308, 607086)
('대구광역시 서구 원대동', 202308, 591534)
('대구광역시 북구 국우동', 202308, 572638)
('대구광역시 달서구 진천동', 202308, 565286)
('대구광역시 북구 팔달동', 202308, 535396)
('대구광역시 수성구 중동', 202308, 521414)
('대구광역시 중구 동', 202308, 518796)
('대구광역시 수성구 신매동', 202308, 487605)
('대구광역시 북구 대현동', 202309, 484369)
('대구광역시 북구 구암동', 202308, 480310)
('대구광역시 달서구 성당동', 202308, 478364)
('대구광역시 북구 연경동', 202309, 466100)
('대구광역시 수성구 시지동', 202308, 465322)
('대구광역시 중구 공평동', 202308, 461038)
('대구광역시 수성구 노변동', 202308, 456116)
('대구광역시 달서구 장동', 202302, 454608)
('대구광역시 북구 검단동', 202309, 447427)
('대구광역시 수성구 파동', 202309, 442657)
('대구광역시 북구 읍내동', 202309, 442088)
('대구광역시 중구 문화동', 202301, 439056)
('대구광역시 달서구 송현동', 202308, 420393)
('대구광역시 수성구 매호동', 202308, 407033)
('대구광역시 달서구 본동', 202308, 393904)
('대구광역시 수성구 지산동', 202308, 351171)
('대구광역시 서구 상리동', 202309, 349095)
('대구광역시 남구 이천동', 202308, 326799)
('대구광역시 수성구 욱수동', 202309, 278003)
('대구광역시 중구 수동', 202308, 236175)
('대구광역시 중구 향촌동', 202308, 227740)
('대구광역시 중구 봉산동', 202308, 223201)
('대구광역시 달서구 죽전동', 202308, 221923)
('대구광역시 달서구 호림동', 202301, 207409)
('대구광역시 중구 남일동', 202308, 206856)
('대구광역시 수성구 삼덕동', 202307, 180601)
('대구광역시 수성구 고모동', 202302, 173269)
('대구광역시 달서구 갈산동', 202308, 162133)
('대구광역시 중구 포정동', 202308, 159350)
('대구광역시 중구 교동', 202308, 154066)
('대구광역시 북구 금호동', 202301, 135757)
('대구광역시 북구 도남동', 202301, 135256)
('대구광역시 중구 하서동', 202309, 123441)
('대구광역시 중구 사일동', 202309, 104379)
('대구광역시 수성구 연호동', 202308, 82979)
('대구광역시 중구 인교동', 202307, 64332)
('대구광역시 중구 달성동', 202301, 44615)
('대구광역시 수성구 이천동', 202308, 37904)
('대구광역시 중구 전동', 202301, 37255)
('대구광역시 중구 대안동', 202301, 34394)
('대구광역시 중구 북내동', 202308, 31147)
('대구광역시 중구 서야동', 202301, 26065)
('대구광역시 중구 상서동', 202308, 25531)
('대구광역시 중구 서내동', 202301, 21165)
('대구광역시 중구 장관동', 202308, 17618)
('대구광역시 북구 조야동', 202308, 17250)
('대구광역시 달성군 하빈면 동', 202301, 13971)
('대구광역시 중구 완전동', 202308, 13948)
('대구광역시 수성구 가천동', 202308, 12577)
('대구광역시 중구 화전동', 202301, 11095)
('대구광역시 중구 용덕동', 202302, 10587)
('대구광역시 북구 노곡동', 202308, 9348)
('대구광역시 중구 상덕동', 202302, 8855)
('대구광역시 달성군 구지면 도동', 202301, 5114)
('대구광역시 수성구 성동', 202309, 4135)
('대구광역시 중구 도원동', 202301, 1130)

In [ ]:
#10
import sqlite3

# SQLite 데이터베이스 파일 연결
conn = sqlite3.connect("your_database.db")  # 파일명에 맞게 수정

# 커서 객체 생성
cursor = conn.cursor()
with engine.connect() as conn:
    result = conn.execute(text("""SELECT
    SUBSTR(b.pnu, 1, 10) AS 동코드,
    COUNT(*) AS 건물수
FROM building b
WHERE b.pnu LIKE '27290%'
GROUP BY 동코드;


"""))
# 쿼리 정의


# 쿼리 실행
# cursor.execute(query)

In [ ]:
rows = result.fetchall()
# 출력
for row in rows:
    print(row)

('2729010100', 474)
('2729010200', 897)
('2729010400', 74)
('2729010500', 141)
('2729010600', 241)
('2729010700', 462)
('2729010800', 296)
('2729010900', 175)
('2729011000', 252)
('2729011100', 390)
('2729011200', 256)
('2729011300', 729)
('2729011400', 153)
('2729011500', 662)
('2729011600', 103)
('2729011700', 428)
('2729011800', 50)
('2729011900', 224)
('2729012000', 156)
('2729012100', 210)
('2729012200', 1217)
('2729012300', 91)
('2729012400', 183)
('2729012500', 277)

In [ ]:
#10
import sqlite3

# SQLite 데이터베이스 파일 연결
conn = sqlite3.connect("your_database.db")  # 파일명에 맞게 수정

# 커서 객체 생성
cursor = conn.cursor()
with engine.connect() as conn:
    result = conn.execute(text("""SELECT
    SUBSTR(p.pnu, 1, 10) AS 동코드,
    SUM(CAST("2023년_총인구수" AS INTEGER)) AS 총인구
FROM population p
WHERE p.pnu LIKE '27290%' AND "2023년_총인구수" IS NOT NULL
GROUP BY 동코드;

"""))
# 쿼리 정의


# 쿼리 실행
# cursor.execute(query)

In [ ]:
rows = result.fetchall()
# 출력
for row in rows:
    print(row)

('272900', 537)
('2729051500', 22)
('2729053500', 14)
('2729055000', 8)
('2729055500', 28)
('2729056300', 12)
('2729056800', 16)
('2729057100', 29)
('2729057200', 27)
('2729057600', 22)
('2729057700', 15)
('2729058500', 30)
('2729059000', 19)
('2729060100', 40)
('2729060200', 15)
('2729061500', 51)
('2729061700', 33)
('2729062400', 34)
('2729062500', 18)
('2729062600', 10)
('2729062800', 34)
('2729063000', 18)
('2729064000', 17)
('2729065000', 11)

In [ ]:
#10
import sqlite3

# SQLite 데이터베이스 파일 연결
conn = sqlite3.connect("your_database.db")  # 파일명에 맞게 수정

# 커서 객체 생성
cursor = conn.cursor()
with engine.connect() as conn:
    result = conn.execute(text("""SELECT
    SUBSTR(e.pnu, 1, 10) AS 동코드,
    SUM(전기사용량) AS 총사용량,
    AVG(전기사용량) AS 평균사용량
FROM energy_usage e
WHERE e.pnu LIKE '27290%' AND 사용년월 BETWEEN 202301 AND 202312
GROUP BY 동코드;

"""))
# 쿼리 정의


# 쿼리 실행
# cursor.execute(query)

In [ ]:
rows = result.fetchall()
# 출력
for row in rows:
    print(row)

('2729010100', 45611155, 7231.83050578722)
('2729010200', 68431124, 8314.838882138518)
('2729010400', 18008216, 31760.522045855378)
('2729010500', 16029826, 8585.873594001072)
('2729010600', 14244792, 6113.644635193133)
('2729010700', 70344596, 30771.91426071741)
('2729010800', 108893790, 23922.185852372582)
('2729010900', 10181287, 4666.034372135656)
('2729011000', 38164604, 10957.394200401952)
('2729011100', 112857854, 40465.347436357115)
('2729011200', 22037438, 6856.701306782825)
('2729011300', 87245116, 13874.85941475827)
('2729011400', 48270558, 15631.65738341969)
('2729011500', 152455791, 22822.723203592814)
('2729011600', 79644408, 36500.645279560034)
('2729011700', 77897562, 13774.988859416446)
('2729011800', 51927773, 38014.47510980966)
('2729011900', 59219195, 31399.361081654293)
('2729012000', 140947967, 33384.17029843676)
('2729012100', 16063442, 9101.10028328612)
('2729012200', 66512986, 6750.531411752766)
('2729012300', 56140282, 23275.40713101161)
('2729012400', 28723947, 10350.971891891892)
('2729012500', 34417923, 10499.67144600366)

In [ ]:
# prompt: building, elec2324, po csv로 저장

po.to_csv('po.csv', index=False, encoding='utf-8-sig')
building.to_csv('building.csv', index=False, encoding='utf-8-sig')
elec2324.to_csv('elec2324.csv', index=False, encoding='utf-8-sig')

In [ ]:
#10
import sqlite3

# SQLite 데이터베이스 파일 연결
conn = sqlite3.connect("your_database.db")  # 파일명에 맞게 수정

# 커서 객체 생성
cursor = conn.cursor()
with engine.connect() as conn:
    result = conn.execute(text("""WITH 수성구_건물수 AS (
    SELECT
        SUBSTR(pnu, 1, 10) AS 동코드,
        COUNT(*) AS 건물수
    FROM building
    WHERE pnu LIKE '27290%'
    GROUP BY 동코드
),
수성구_인구 AS (
    SELECT
        SUBSTR(pnu, 1, 10) AS 동코드,
        SUM(CAST("2023년_총인구수" AS INTEGER)) AS 총인구
    FROM population
    WHERE pnu LIKE '27290%'
    GROUP BY 동코드
),
수성구_전기 AS (
    SELECT
        SUBSTR(pnu, 1, 10) AS 동코드,
        SUM(전기사용량) AS 총사용량,
        AVG(전기사용량) AS 평균사용량
    FROM energy_usage
    WHERE pnu LIKE '27290%' AND 사용년월 BETWEEN 202301 AND 202312
    GROUP BY 동코드
),
통합 AS (
    SELECT
        b.동코드,
        b.건물수,
        i.총인구,
        CAST(b.건물수 AS FLOAT) / NULLIF(i.총인구, 0) AS 건물_인구비율,
        e.총사용량,
        e.평균사용량
    FROM 수성구_건물수 b
    JOIN 수성구_인구 i ON b.동코드 = i.동코드
    JOIN 수성구_전기 e ON b.동코드 = e.동코드
)
-- 건물 밀집 동 5개와 일반 동 5개 비교
SELECT * FROM 통합
ORDER BY 건물_인구비율 DESC
LIMIT 10;


"""))
# 쿼리 정의


# 쿼리 실행
# cursor.execute(query)

In [ ]:
rows = result.fetchall()
# 출력
for row in rows:
    print(row)

2023년01월_총인구수
2023년01월_세대수
2023년01월_세대당 인구
2023년01월_남자 인구수
2023년01월_여자 인구수
2023년01월_남여 비율
2024년01월_총인구수
2024년01월_세대수
2024년01월_세대당 인구
2024년01월_남자 인구수
2024년01월_여자 인구수
2024년01월_남여 비율
pnu